begin;

create extension if not exists pgcrypto;

insert into storage.buckets (id, name, public, file_size_limit)
values ('rps-attachments-backup', 'rps-attachments-backup', false, 20971520)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit;

create table if not exists public.rps_backup_runs (
  id                  uuid primary key default gen_random_uuid(),
  organization_id     uuid not null references public.organizations(id) on delete cascade,
  ano                 integer not null check (ano between 2000 and 2200),
  mes                 integer not null check (mes between 1 and 12),
  kind                text not null check (kind in ('scheduled', 'manual', 'pre_restore')),
  status              text not null default 'building' check (status in ('building', 'ready', 'failed', 'expired')),
  captured_at         timestamptz not null default now(),
  completed_at        timestamptz,
  retention_until     timestamptz not null default (now() + interval '6 months'),
  source_version      bigint not null,
  source_updated_at   timestamptz,
  snapshot_hash       text not null,
  storage_prefix      text not null unique,
  expected_file_count integer not null default 0 check (expected_file_count >= 0),
  verified_file_count integer not null default 0 check (verified_file_count >= 0),
  expected_bytes      bigint not null default 0 check (expected_bytes >= 0),
  verified_bytes      bigint not null default 0 check (verified_bytes >= 0),
  created_by          uuid references auth.users(id) on delete set null,
  source_restore_id   uuid,
  error_message       text,
  metadata            jsonb not null default '{}'::jsonb
);

create index if not exists rps_backup_runs_period_idx
  on public.rps_backup_runs (organization_id, ano, mes, captured_at desc);
create index if not exists rps_backup_runs_retention_idx
  on public.rps_backup_runs (retention_until)
  where status in ('ready', 'failed');

create table if not exists public.rps_backup_snapshots (
  run_id              uuid primary key references public.rps_backup_runs(id) on delete cascade,
  payload             jsonb not null,
  source_version      bigint not null,
  source_updated_at   timestamptz,
  snapshot_hash       text not null,
  created_at          timestamptz not null default now()
);

create table if not exists public.rps_backup_files (
  id                  bigint generated by default as identity primary key,
  run_id              uuid not null references public.rps_backup_runs(id) on delete cascade,
  original_path       text not null,
  backup_path         text not null,
  size_bytes          bigint not null check (size_bytes >= 0),
  sha256              text not null,
  content_type        text,
  created_at          timestamptz not null default now(),
  unique (run_id, original_path),
  unique (backup_path)
);

create index if not exists rps_backup_files_run_idx
  on public.rps_backup_files (run_id);

create table if not exists public.rps_restore_operations (
  id                    uuid primary key default gen_random_uuid(),
  organization_id       uuid not null references public.organizations(id) on delete cascade,
  ano                   integer not null check (ano between 2000 and 2200),
  mes                   integer not null check (mes between 1 and 12),
  backup_run_id         uuid not null references public.rps_backup_runs(id),
  safety_backup_run_id  uuid references public.rps_backup_runs(id),
  status                text not null default 'preparing'
                          check (status in ('preparing', 'running', 'succeeded', 'failed', 'rolled_back', 'rollback_failed')),
  phase                 text not null default 'lock_acquired',
  initiated_by          uuid not null references auth.users(id) on delete restrict,
  started_at            timestamptz not null default now(),
  finished_at           timestamptz,
  target_version_before bigint,
  target_version_after  bigint,
  files_replaced        integer not null default 0,
  bytes_replaced        bigint not null default 0,
  error_message         text,
  rollback_error        text,
  details               jsonb not null default '{}'::jsonb
);

create index if not exists rps_restore_operations_period_idx
  on public.rps_restore_operations (organization_id, ano, mes, started_at desc);

create table if not exists public.rps_maintenance_locks (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  ano             integer not null,
  mes             integer not null,
  restore_id      uuid unique references public.rps_restore_operations(id) on delete cascade,
  backup_run_id   uuid unique,
  lock_reason     text not null check (lock_reason in ('backup', 'restore')),
  locked_by       uuid references auth.users(id) on delete restrict,
  locked_at       timestamptz not null default now(),
  expires_at      timestamptz not null default (now() + interval '2 hours'),
  primary key (organization_id, ano, mes),
  check (num_nonnulls(restore_id, backup_run_id) = 1)
);

alter table public.rps_backup_runs enable row level security;
alter table public.rps_backup_snapshots enable row level security;
alter table public.rps_backup_files enable row level security;
alter table public.rps_restore_operations enable row level security;
alter table public.rps_maintenance_locks enable row level security;

create or replace function public.is_rps_admin(target_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.get_my_access_role(target_organization_id) in ('admin', 'super_admin')
$$;

grant execute on function public.is_rps_admin(uuid) to authenticated;

drop policy if exists "rps admins read backup runs" on public.rps_backup_runs;
create policy "rps admins read backup runs"
on public.rps_backup_runs for select to authenticated
using (public.is_rps_admin(organization_id));

drop policy if exists "rps admins read backup snapshots" on public.rps_backup_snapshots;
create policy "rps admins read backup snapshots"
on public.rps_backup_snapshots for select to authenticated
using (
  exists (
    select 1 from public.rps_backup_runs r
    where r.id = run_id and public.is_rps_admin(r.organization_id)
  )
);

drop policy if exists "rps admins read backup files" on public.rps_backup_files;
create policy "rps admins read backup files"
on public.rps_backup_files for select to authenticated
using (
  exists (
    select 1 from public.rps_backup_runs r
    where r.id = run_id and public.is_rps_admin(r.organization_id)
  )
);

drop policy if exists "rps admins read restore operations" on public.rps_restore_operations;
create policy "rps admins read restore operations"
on public.rps_restore_operations for select to authenticated
using (public.is_rps_admin(organization_id));

drop policy if exists "org members read rps maintenance lock" on public.rps_maintenance_locks;
create policy "org members read rps maintenance lock"
on public.rps_maintenance_locks for select to authenticated
using (public.is_org_member(organization_id));

grant select on public.rps_backup_runs, public.rps_backup_snapshots,
  public.rps_backup_files, public.rps_restore_operations,
  public.rps_maintenance_locks to authenticated;

create or replace function public.rps_capture_backup(
  p_organization_id uuid,
  p_ano integer,
  p_mes integer,
  p_kind text,
  p_created_by uuid default null,
  p_source_restore_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_snapshot public.rps_snapshots%rowtype;
  v_run_id uuid := gen_random_uuid();
  v_hash text;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'rps_capture_backup exige service_role';
  end if;
  if p_kind not in ('scheduled', 'manual', 'pre_restore') then
    raise exception 'Tipo de backup invalido';
  end if;

  if p_kind <> 'pre_restore' then
    lock table public.rps_snapshots in share mode;
    lock table storage.objects in share mode;
    begin
      insert into public.rps_maintenance_locks (
        organization_id, ano, mes, backup_run_id, lock_reason, locked_by
      ) values (
        p_organization_id, p_ano, p_mes, v_run_id, 'backup', p_created_by
      );
    exception when unique_violation then
      raise exception 'Periodo temporariamente bloqueado por outra operacao';
    end;
  end if;

  select * into v_snapshot
  from public.rps_snapshots
  where organization_id = p_organization_id and ano = p_ano and mes = p_mes
  for share;

  if not found then
    raise exception 'Snapshot RPS %/% nao encontrado', p_mes, p_ano;
  end if;

  v_hash := encode(digest(convert_to(v_snapshot.payload::text, 'UTF8'), 'sha256'), 'hex');

  insert into public.rps_backup_runs (
    id, organization_id, ano, mes, kind, status, retention_until,
    source_version, source_updated_at, snapshot_hash, storage_prefix,
    created_by, source_restore_id
  ) values (
    v_run_id, p_organization_id, p_ano, p_mes, p_kind, 'building',
    now() + interval '6 months', v_snapshot.version, v_snapshot.updated_at,
    v_hash,
    v_run_id::text || '/' || p_organization_id::text || '/' ||
      p_ano::text || '-' || lpad(p_mes::text, 2, '0'),
    p_created_by, p_source_restore_id
  );

  insert into public.rps_backup_snapshots (
    run_id, payload, source_version, source_updated_at, snapshot_hash
  ) values (
    v_run_id, v_snapshot.payload, v_snapshot.version, v_snapshot.updated_at, v_hash
  );

  return v_run_id;
end;
$$;

create or replace function public.rps_start_restore(
  p_organization_id uuid,
  p_ano integer,
  p_mes integer,
  p_backup_run_id uuid,
  p_initiated_by uuid
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_run public.rps_backup_runs%rowtype;
  v_restore_id uuid := gen_random_uuid();
  v_current_version bigint;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'rps_start_restore exige service_role';
  end if;

  select * into v_run from public.rps_backup_runs
  where id = p_backup_run_id for share;
  if not found or v_run.organization_id <> p_organization_id
    or v_run.ano <> p_ano or v_run.mes <> p_mes
    or v_run.status <> 'ready' or v_run.retention_until <= now() then
    raise exception 'Backup indisponivel para este periodo';
  end if;

  lock table public.rps_snapshots in share mode;
  lock table storage.objects in share mode;

  delete from public.rps_maintenance_locks
  where organization_id = p_organization_id and ano = p_ano and mes = p_mes
    and expires_at <= now();

  select version into v_current_version from public.rps_snapshots
  where organization_id = p_organization_id and ano = p_ano and mes = p_mes;

  insert into public.rps_restore_operations (
    id, organization_id, ano, mes, backup_run_id, initiated_by,
    target_version_before
  ) values (
    v_restore_id, p_organization_id, p_ano, p_mes, p_backup_run_id,
    p_initiated_by, v_current_version
  );

  begin
    insert into public.rps_maintenance_locks (
      organization_id, ano, mes, restore_id, lock_reason, locked_by
    ) values (
      p_organization_id, p_ano, p_mes, v_restore_id, 'restore', p_initiated_by
    );
  exception when unique_violation then
    delete from public.rps_restore_operations where id = v_restore_id;
    raise exception 'Ja existe uma restauracao em andamento para este periodo';
  end;

  return v_restore_id;
end;
$$;

create or replace function public.rps_apply_restore_snapshot(p_restore_id uuid)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_op public.rps_restore_operations%rowtype;
  v_backup public.rps_backup_snapshots%rowtype;
  v_hash text;
  v_version bigint;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'rps_apply_restore_snapshot exige service_role';
  end if;

  select * into v_op from public.rps_restore_operations
  where id = p_restore_id for update;
  if not found or v_op.status not in ('preparing', 'running') then
    raise exception 'Operacao de restauracao invalida';
  end if;

  select * into v_backup from public.rps_backup_snapshots
  where run_id = v_op.backup_run_id;
  if not found then raise exception 'Snapshot do backup nao encontrado'; end if;

  v_hash := encode(digest(convert_to(v_backup.payload::text, 'UTF8'), 'sha256'), 'hex');
  if v_hash <> v_backup.snapshot_hash then
    raise exception 'Hash do snapshot de backup invalido';
  end if;

  insert into public.rps_snapshots (
    organization_id, ano, mes, payload, version, created_by, updated_by
  ) values (
    v_op.organization_id, v_op.ano, v_op.mes, v_backup.payload, 1,
    v_op.initiated_by, v_op.initiated_by
  )
  on conflict (organization_id, ano, mes) do update
  set payload = excluded.payload,
      version = public.rps_snapshots.version + 1,
      updated_by = v_op.initiated_by
  returning version into v_version;

  update public.rps_restore_operations
  set status = 'running', phase = 'database_applied', target_version_after = v_version
  where id = p_restore_id;
  return v_version;
end;
$$;

create or replace function public.rps_rollback_restore_snapshot(p_restore_id uuid)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_op public.rps_restore_operations%rowtype;
  v_backup public.rps_backup_snapshots%rowtype;
  v_hash text;
  v_version bigint;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'rps_rollback_restore_snapshot exige service_role';
  end if;
  select * into v_op from public.rps_restore_operations where id = p_restore_id for update;
  if not found or v_op.safety_backup_run_id is null then
    raise exception 'Backup de seguranca nao encontrado';
  end if;
  select * into v_backup from public.rps_backup_snapshots
  where run_id = v_op.safety_backup_run_id;
  if not found then raise exception 'Snapshot de seguranca nao encontrado'; end if;
  v_hash := encode(digest(convert_to(v_backup.payload::text, 'UTF8'), 'sha256'), 'hex');
  if v_hash <> v_backup.snapshot_hash then raise exception 'Hash do snapshot de seguranca invalido'; end if;

  insert into public.rps_snapshots (
    organization_id, ano, mes, payload, version, created_by, updated_by
  ) values (
    v_op.organization_id, v_op.ano, v_op.mes, v_backup.payload, 1,
    v_op.initiated_by, v_op.initiated_by
  )
  on conflict (organization_id, ano, mes) do update
  set payload = excluded.payload,
      version = public.rps_snapshots.version + 1,
      updated_by = v_op.initiated_by
  returning version into v_version;
  return v_version;
end;
$$;

create or replace function public.rps_finish_restore(
  p_restore_id uuid,
  p_status text,
  p_phase text,
  p_error_message text default null,
  p_rollback_error text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'rps_finish_restore exige service_role';
  end if;
  if p_status not in ('succeeded', 'failed', 'rolled_back', 'rollback_failed') then
    raise exception 'Status final invalido';
  end if;
  update public.rps_restore_operations
  set status = p_status, phase = p_phase, error_message = p_error_message,
      rollback_error = p_rollback_error, finished_at = now()
  where id = p_restore_id;
  delete from public.rps_maintenance_locks where restore_id = p_restore_id;
end;
$$;

create or replace function public.rps_reject_write_while_locked()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org uuid := case when tg_op = 'DELETE' then old.organization_id else new.organization_id end;
  v_ano integer := case when tg_op = 'DELETE' then old.ano else new.ano end;
  v_mes integer := case when tg_op = 'DELETE' then old.mes else new.mes end;
begin
  if coalesce(auth.role(), '') = 'service_role' then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;
  if exists (
    select 1 from public.rps_maintenance_locks
    where organization_id = v_org and ano = v_ano and mes = v_mes and expires_at > now()
  ) then
    raise exception using
      errcode = '55006',
      message = 'RPS_LOCKED_FOR_RESTORE',
      detail = 'Este periodo esta temporariamente bloqueado para restauracao.';
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists trg_rps_snapshots_restore_lock on public.rps_snapshots;
create trigger trg_rps_snapshots_restore_lock
before insert or update or delete on public.rps_snapshots
for each row execute function public.rps_reject_write_while_locked();

create or replace function public.rps_attachment_period_unlocked(object_name text)
returns boolean
language plpgsql
stable
security definer
set search_path = public, storage
as $$
declare
  v_parts text[] := storage.foldername(object_name);
  v_org uuid;
  v_ano integer;
  v_mes integer;
begin
  if coalesce(auth.role(), '') = 'service_role' then return true; end if;
  if array_length(v_parts, 1) < 2
    or v_parts[1] !~ '^[0-9a-fA-F-]{36}$'
    or v_parts[2] !~ '^\d{4}-\d{2}$' then
    return false;
  end if;
  v_org := v_parts[1]::uuid;
  v_ano := split_part(v_parts[2], '-', 1)::integer;
  v_mes := split_part(v_parts[2], '-', 2)::integer;
  return not exists (
    select 1 from public.rps_maintenance_locks
    where organization_id = v_org and ano = v_ano and mes = v_mes and expires_at > now()
  );
end;
$$;

grant execute on function public.rps_attachment_period_unlocked(text) to authenticated;

drop policy if exists "org editors upload rps attachments" on storage.objects;
create policy "org editors upload rps attachments"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'rps-attachments'
  and (storage.foldername(name))[1] ~ '^[0-9a-fA-F-]{36}$'
  and public.is_org_editor(((storage.foldername(name))[1])::uuid)
  and public.rps_attachment_period_unlocked(name)
);

drop policy if exists "org editors update rps attachments" on storage.objects;
create policy "org editors update rps attachments"
on storage.objects for update to authenticated
using (
  bucket_id = 'rps-attachments'
  and (storage.foldername(name))[1] ~ '^[0-9a-fA-F-]{36}$'
  and public.is_org_editor(((storage.foldername(name))[1])::uuid)
  and public.rps_attachment_period_unlocked(name)
)
with check (
  bucket_id = 'rps-attachments'
  and (storage.foldername(name))[1] ~ '^[0-9a-fA-F-]{36}$'
  and public.is_org_editor(((storage.foldername(name))[1])::uuid)
  and public.rps_attachment_period_unlocked(name)
);

drop policy if exists "org editors delete rps attachments" on storage.objects;
create policy "org editors delete rps attachments"
on storage.objects for delete to authenticated
using (
  bucket_id = 'rps-attachments'
  and (storage.foldername(name))[1] ~ '^[0-9a-fA-F-]{36}$'
  and public.is_org_editor(((storage.foldername(name))[1])::uuid)
  and public.rps_attachment_period_unlocked(name)
);

revoke all on function public.rps_capture_backup(uuid, integer, integer, text, uuid, uuid) from public, authenticated;
revoke all on function public.rps_start_restore(uuid, integer, integer, uuid, uuid) from public, authenticated;
revoke all on function public.rps_apply_restore_snapshot(uuid) from public, authenticated;
revoke all on function public.rps_rollback_restore_snapshot(uuid) from public, authenticated;
revoke all on function public.rps_finish_restore(uuid, text, text, text, text) from public, authenticated;
grant execute on function public.rps_capture_backup(uuid, integer, integer, text, uuid, uuid) to service_role;
grant execute on function public.rps_start_restore(uuid, integer, integer, uuid, uuid) to service_role;
grant execute on function public.rps_apply_restore_snapshot(uuid) to service_role;
grant execute on function public.rps_rollback_restore_snapshot(uuid) to service_role;
grant execute on function public.rps_finish_restore(uuid, text, text, text, text) to service_role;
grant all on public.rps_backup_runs, public.rps_backup_snapshots,
  public.rps_backup_files, public.rps_restore_operations,
  public.rps_maintenance_locks to service_role;
grant usage, select on sequence public.rps_backup_files_id_seq to service_role;

comment on table public.rps_backup_runs is
  'Backups verificaveis por organizacao e periodo da RPS; somente status ready pode ser restaurado.';
comment on table public.rps_restore_operations is
  'Auditoria e maquina de estados das restauracoes da RPS, incluindo backup de seguranca e rollback.';

commit;
