(function attachVectonComercialPecasGeo(window) {
  function createComercialPecasGeoModule(deps) {
    const { escapeHtml, state, resolveOrganizationId, callSupabaseRpc, isSupabaseConfigured } = deps;
    const REPORT_ID = "comercialPecasGeo";
    const ICON_STROKE_WIDTH = 1.8;
    const ICON_SIZE_DEFAULT = 16;
    const ICON_SIZE_KPI = 20;
    const UFS = ["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO","EX"];
    const BR = window.VECTON_BR_GEO || { bbox: [-74,-34,-32,6], states: [] };
    const [minx,miny,maxx,maxy] = BR.bbox;
    const kx = Math.cos(((miny + maxy) / 2) * Math.PI / 180);
    const gW = (maxx-minx)*kx, gH = maxy-miny, VW=1000, VH=Math.round(VW*gH/gW);
    const proj = (lo,la) => [(lo-minx)*kx/gW*VW,(maxy-la)/gH*VH];
    const statePath = (rings) => rings.map((r)=>"M"+r.map(([lo,la])=>{const [x,y]=proj(lo,la);return `${x.toFixed(1)},${y.toFixed(1)}`;}).join("L")+"Z").join(" ");
    const STATE_NAMES = Object.fromEntries(BR.states.map((s)=>[s.uf,s.nome]));
    const GLOSSARY = [
      {group:"KPIs",title:"Faturamento Peças",formula:"Soma do valor faturado das linhas classificadas como Peças.",read:"Responde quanto foi vendido no universo filtrado. Deve reconciliar exatamente com Peças no Painel de Vendas."},
      {group:"KPIs",title:"Clientes compradores",formula:"Contagem de clientes únicos com faturamento no período.",read:"Mede a amplitude da carteira ativa. Crescimento indica que mais clientes diferentes compraram peças."},
      {group:"KPIs",title:"Notas fiscais",formula:"Contagem distinta de documento e série da NF.",read:"Representa eventos de compra, não linhas ou SKUs. “Base documental parcial” indica que parte do histórico não possui documento/série."},
      {group:"KPIs",title:"Faturamento médio por cliente",formula:"Faturamento ÷ clientes compradores.",read:"Mostra o valor médio gerado por cliente. Um aumento pode vir de maior ticket, maior frequência ou concentração em poucos clientes."},
      {group:"KPIs",title:"Compras por cliente",formula:"Notas fiscais distintas ÷ clientes compradores.",read:"É a frequência média de compra no período. Valores acima de 1 indicam repetição de compra na carteira."},
      {group:"KPIs",title:"Territórios atendidos",formula:"Quantidade de UFs com venda, acrescida de EX quando houver exterior.",read:"Mede cobertura geográfica. EX é tratado separadamente e não como uma UF brasileira."},
      {group:"Geografia",title:"Mapa — Faturamento",formula:"Intensidade da cor proporcional ao faturamento de cada UF.",read:"Estados mais intensos concentram maior valor vendido. Clique numa UF para filtrar todo o relatório."},
      {group:"Geografia",title:"Mapa — Clientes",formula:"Intensidade da cor proporcional aos clientes únicos de cada UF.",read:"Ajuda a diferenciar mercados amplos de mercados concentrados em poucos compradores."},
      {group:"Geografia",title:"Mapa — Recorrência",formula:"Compras distintas ÷ clientes, calculado por UF.",read:"Destaca onde a carteira compra com maior frequência; não representa quantidade absoluta de NFs."},
      {group:"Geografia",title:"Rankings geográficos",formula:"Ordenação das UFs/EX por faturamento, clientes ou compras por cliente.",read:"O percentual é calculado sobre o universo filtrado. A barra compara cada território ao líder da métrica."},
      {group:"Carteira",title:"Top municípios",formula:"Municípios ordenados por faturamento, com clientes, NFs e média por cliente.",read:"Identifica polos locais relevantes. Quando uma UF é selecionada, o ranking passa a refletir somente aquela UF."},
      {group:"Carteira",title:"Top clientes",formula:"Clientes ordenados por faturamento decrescente.",read:"NFs/Compras mostram frequência; Última compra e Dias sem comprar ajudam a avaliar recência sem classificar o cliente como ativo ou inativo."},
      {group:"Carteira",title:"Distribuição por faixa de faturamento",formula:"Cada cliente é classificado pelo faturamento acumulado no período.",read:"Mostra concentração da carteira por valor. Uma parcela alta nas maiores faixas indica dependência de clientes de maior porte."},
      {group:"Carteira",title:"Distribuição por recorrência",formula:"1 compra; 2–3; 4–6; ou 7+ compras no período.",read:"Cliente recorrente é quem realizou pelo menos duas compras. Use para distinguir alcance de carteira de relacionamento repetido."},
      {group:"Produtos",title:"Top SKUs",formula:"SKUs agrupados pelo código oficial e ordenados por faturamento.",read:"Clientes mede penetração; UFs e Municípios medem dispersão geográfica. Clique no SKU para filtrar todo o relatório."},
      {group:"Leitura",title:"Variação vs. período anterior",formula:"(Valor atual − valor anterior) ÷ valor anterior.",read:"Mês compara com o mês anterior; YTD e Ano comparam a mesma janela do ano anterior. Verde é aumento e vermelho é redução."},
      {group:"Leitura",title:"Participação (%)",formula:"Valor do item ÷ total atualmente filtrado.",read:"Ao selecionar Jenifer, UF, cliente ou SKU, a base do percentual também muda para esse novo universo."}
    ];

    let filters = { periodMode:"mes", seller:"all", state:"", city:"", customerId:"", customerLabel:"", sku:"", skuLabel:"", mapMetric:"revenue" };
    let year = Number(state.currentPeriod?.year || new Date().getFullYear());
    let month = Number(state.currentPeriod?.month || new Date().getMonth()+1);
    let data = null, loading = false, error = "", loadedKey = "", host = null, tooltip = null;
    let expanded = { cities:false, customers:false, skus:false };
    let searchTimer = null, docCloseBound = false, glossaryKeyBound = false, showGlossary = false;

    function ensureStyle() {
      if (document.getElementById("cpg-style")) return;
      const s=document.createElement("style"); s.id="cpg-style"; s.textContent=`
      .cpg{--bg:#090b11;--panel:#11141b;--panel2:#151922;--line:#29303b;--text:#f4f6fb;--muted:#8e98aa;--purple:#8b4cf6;--purple2:#b276ff;--green:#3fd49a;--red:#ff6b7a;color:var(--text);font-size:12px;min-width:0}.cpg *{box-sizing:border-box}.cpg button,.cpg input,.cpg select{font:inherit}.cpg-header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;padding:2px 6px 14px;border-bottom:1px solid var(--line)}.cpg-title h1{font-size:18px;letter-spacing:.01em;margin:0 0 4px}.cpg-title p,.cpg-meta p{margin:0;color:var(--muted)}.cpg-meta{display:flex;flex-direction:column;align-items:flex-end;text-align:right;line-height:1.4}.cpg-help{display:inline-flex;align-items:center;gap:6px;margin-top:6px;border:1px solid var(--line);border-radius:7px;background:var(--panel);color:#d8deea;padding:6px 10px;cursor:pointer}.cpg-help:hover{border-color:var(--purple);color:#fff}.cpg-help svg{color:var(--purple2)}
      .cpg-filters{display:grid;grid-template-columns:192px repeat(5,minmax(135px,1fr)) 140px;gap:10px;padding:13px 6px}.cpg-field{min-width:0;position:relative}.cpg-field>label{display:block;color:#bec5d2;font-size:10px;font-weight:600;margin:0 0 5px;text-transform:uppercase;letter-spacing:.04em}.cpg-control,.cpg-clear{height:34px;width:100%;border:1px solid var(--line);border-radius:7px;background:var(--panel);color:var(--text);padding:0 10px;outline:none}.cpg-control:focus{border-color:var(--purple)}.cpg-control:disabled{opacity:.45}.cpg-period{display:grid;grid-template-columns:repeat(3,1fr);height:34px;border:1px solid var(--line);border-radius:7px;overflow:hidden;background:var(--panel)}.cpg-period button,.cpg-metric button{border:0;background:transparent;color:var(--muted);cursor:pointer}.cpg-period button.active,.cpg-metric button.active{background:linear-gradient(135deg,#6627ce,#8b4cf6);color:white}.cpg-clear{margin-top:15px;color:#d1d6df;display:flex;align-items:center;justify-content:center;gap:7px;cursor:pointer}.cpg-clear:hover{border-color:var(--purple);color:white}.cpg-search-wrap{position:relative}.cpg-search-wrap>svg{position:absolute;right:10px;top:9px;color:var(--muted);pointer-events:none}.cpg-search-wrap input{padding-right:30px}.cpg-suggest{position:absolute;z-index:80;left:0;right:0;top:38px;background:#191d27;border:1px solid var(--line);border-radius:8px;box-shadow:0 18px 40px #0009;max-height:230px;overflow:auto}.cpg-suggest button{width:100%;border:0;border-bottom:1px solid #ffffff0d;background:transparent;color:#dfe4ee;text-align:left;padding:9px 10px;cursor:pointer}.cpg-suggest button:hover{background:#8b4cf61c}.cpg-suggest .empty{padding:10px;color:var(--muted)}
      .cpg-kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin:0 0 8px}.cpg-kpi{min-width:0;border:1px solid var(--line);border-radius:8px;background:linear-gradient(145deg,#12161e,#0f1218);padding:12px;display:flex;gap:11px;align-items:center}.cpg-kpi-icon{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;color:var(--purple2);background:#8b4cf617;border:1px solid #8b4cf63b;box-shadow:0 0 20px #8b4cf61c;flex:none}.cpg-kpi-label{font-size:9.5px;color:#b9c0cd;text-transform:uppercase;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cpg-kpi-value{font-size:17px;font-weight:700;margin:4px 0 2px;white-space:nowrap}.cpg-delta{font-size:9.5px;color:var(--muted);white-space:nowrap}.cpg-delta.pos{color:var(--green)}.cpg-delta.neg{color:var(--red)}
      .cpg-card{background:linear-gradient(145deg,#12161e,#10131a);border:1px solid var(--line);border-radius:8px;min-width:0;overflow:hidden}.cpg-card-head{height:42px;padding:10px 12px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #ffffff09}.cpg-card-head h2{font-size:11px;text-transform:uppercase;margin:0;display:flex;align-items:center;gap:7px}.cpg-card-head h2 svg{color:var(--purple2)}.cpg-card-head p{font-size:10px;color:var(--muted);margin:2px 0 0}.cpg-more{border:1px solid var(--line);border-radius:6px;background:transparent;color:#bfc6d2;font-size:9px;text-transform:uppercase;padding:5px 8px;cursor:pointer}.cpg-more:hover{color:#fff;border-color:var(--purple)}
      .cpg-main{display:grid;grid-template-columns:minmax(410px,1.25fr) minmax(245px,.65fr) minmax(520px,1.4fr);grid-template-rows:224px 224px;gap:8px}.cpg-map-card{grid-row:1/3}.cpg-map-head{height:76px;padding:10px 12px}.cpg-metric{display:flex;width:max-content;height:30px;border:1px solid var(--line);border-radius:6px;overflow:hidden;margin-top:9px}.cpg-metric button{padding:0 14px;font-size:9px;text-transform:uppercase}.cpg-map-area{height:calc(100% - 76px);position:relative;display:flex;align-items:center;justify-content:center;padding:8px}.cpg-map-area svg.map{height:100%;max-width:78%;overflow:visible}.cpg-state{stroke:#a9a4c2;stroke-width:1.25;vector-effect:non-scaling-stroke;cursor:pointer;transition:filter .15s,opacity .15s}.cpg-state:hover,.cpg-state.selected{filter:brightness(1.5) drop-shadow(0 0 4px #a86eff)}.cpg-map-area.ex-selected .cpg-state{opacity:.32;filter:saturate(.2)}.cpg-map-label{fill:#f6f1ff;font-size:18px;font-weight:700;pointer-events:none;text-anchor:middle;paint-order:stroke;stroke:#221c33;stroke-width:4px}.cpg-legend{position:absolute;left:12px;bottom:12px;border:1px solid var(--line);background:#0b0e14dd;border-radius:7px;padding:9px;width:128px}.cpg-legend strong{display:block;font-size:8px;color:#b9c0cd;margin-bottom:6px}.cpg-legend span{display:flex;align-items:center;gap:5px;color:var(--muted);font-size:8px;margin:4px 0}.cpg-legend i{width:9px;height:9px;border-radius:1px}.cpg-ex{position:absolute;right:15px;bottom:15px;border:1px solid var(--line);border-radius:7px;background:#10141c;color:#fff;padding:9px 14px;text-align:left;cursor:pointer}.cpg-ex.active{border-color:var(--purple);box-shadow:0 0 0 1px #8b4cf655}.cpg-ex strong{display:block;font-size:13px}.cpg-ex span{display:block;color:#d8dce5;font-size:10px;margin-top:4px}
      .cpg-ranks{grid-row:1/3;display:grid;grid-template-rows:repeat(3,1fr);gap:8px}.cpg-rank{padding:8px 10px}.cpg-rank h3{font-size:10px;text-transform:uppercase;margin:0 0 6px;display:flex;gap:6px;align-items:center}.cpg-rank h3 svg{color:var(--purple2)}.cpg-rank-row{display:grid;grid-template-columns:14px 24px 1fr 42px;gap:5px;align-items:center;height:24px;color:#dfe3eb;cursor:pointer}.cpg-rank-row .pos{color:#8d96a6}.cpg-rank-row .pct{text-align:right;color:#bec5d0;font-size:9px}.cpg-barline{display:flex;align-items:center;gap:6px;min-width:0}.cpg-barline b{font-size:9px;white-space:nowrap}.cpg-bar{height:6px;flex:1;background:#202530;border-radius:5px;overflow:hidden}.cpg-bar i{display:block;height:100%;border-radius:5px;background:linear-gradient(90deg,#6e2dd8,#ad72ff)}
      .cpg-table{width:100%;border-collapse:collapse;table-layout:auto}.cpg-table th,.cpg-table td{padding:8px 10px;border-bottom:1px solid #ffffff0c;text-align:left;white-space:nowrap;font-size:9.5px}.cpg-table th{color:#8f99aa;font-weight:500}.cpg-table td{color:#dce1ea}.cpg-table .num{text-align:right;font-variant-numeric:tabular-nums}.cpg-table tbody tr.clickable{cursor:pointer}.cpg-table tbody tr.clickable:hover{background:#8b4cf610}.cpg-table-wrap{overflow:auto;height:calc(100% - 42px)}.cpg-city{grid-column:3}.cpg-customer{grid-column:3}.cpg-bottom{display:grid;grid-template-columns:minmax(300px,.8fr) minmax(300px,.8fr) minmax(600px,1.8fr);gap:8px;margin-top:8px;height:205px}.cpg-dist{display:grid;grid-template-columns:105px 1fr;gap:9px;align-items:center;padding:9px 12px;height:calc(100% - 42px)}.cpg-donut{width:92px;height:92px;border-radius:50%;position:relative}.cpg-donut:after{content:"";position:absolute;inset:23px;border-radius:50%;background:#12161e}.cpg-dist-row{display:grid;grid-template-columns:1fr 34px 32px;gap:5px;height:20px;align-items:center;font-size:8.5px}.cpg-dist-row .dot{width:7px;height:7px;border-radius:2px;display:inline-block;margin-right:5px}.cpg-dist-row b,.cpg-dist-row em{text-align:right;font-style:normal}.cpg-dist-foot{grid-column:1/3;border-top:1px solid var(--line);padding-top:6px;display:flex;justify-content:space-between;color:#dfe4ec;font-size:9px}.cpg-compliance{margin-top:8px;border:1px solid var(--line);border-radius:8px;background:#10131a;padding:10px 12px;display:flex;justify-content:space-between;gap:20px;color:#8994a5;font-size:9.5px}.cpg-compliance span:first-child{display:flex;align-items:center;gap:6px}.cpg-compliance svg{color:#6aa1ff}.cpg-empty{border:1px solid var(--line);border-radius:8px;background:var(--panel);padding:70px;text-align:center;color:var(--muted)}.cpg-empty button{margin-top:12px}.cpg-skeleton{animation:cpgPulse 1.3s infinite alternate;opacity:.58;pointer-events:none}@keyframes cpgPulse{to{opacity:.82}}.cpg-tt{position:fixed;z-index:9999;pointer-events:none;width:230px;background:#10141dec;border:1px solid #394253;border-radius:8px;padding:11px;box-shadow:0 18px 50px #000b;color:#e9edf5;font-size:10px;line-height:1.65}.cpg-tt strong{display:block;font-size:12px;margin-bottom:5px}.cpg-tt .row{display:flex;justify-content:space-between;gap:10px}.cpg-warning{color:#f5c76a!important}
      .cpg-glossary-backdrop{position:fixed;inset:0;z-index:10020;background:#03050acc;display:grid;place-items:center;padding:24px}.cpg-glossary{width:min(1080px,94vw);height:min(760px,90vh);display:flex;flex-direction:column;background:#11151d;border:1px solid #353d4a;border-radius:14px;box-shadow:0 30px 90px #000d;overflow:hidden;text-align:left}.cpg-glossary-head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;padding:18px 20px;border-bottom:1px solid var(--line)}.cpg-glossary-head h2{font-size:16px;margin:0 0 4px;display:flex;align-items:center;gap:8px}.cpg-glossary-head h2 svg{color:var(--purple2)}.cpg-glossary-head p{margin:0;color:var(--muted);font-size:11px}.cpg-glossary-close{width:32px;height:32px;display:grid;place-items:center;border:1px solid var(--line);border-radius:7px;background:#171b24;color:#cbd2dd;cursor:pointer}.cpg-glossary-close:hover{border-color:var(--purple);color:#fff}.cpg-glossary-body{overflow:auto;padding:16px 20px 22px}.cpg-glossary-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.cpg-glossary-item{border:1px solid #29313d;border-radius:9px;background:#0d1118;padding:12px 14px}.cpg-glossary-group{display:block;color:var(--purple2);font-size:8.5px;font-weight:700;text-transform:uppercase;letter-spacing:.08em;margin-bottom:4px}.cpg-glossary-item h3{font-size:11.5px;margin:0 0 7px;color:#f0f3f8}.cpg-glossary-item p{font-size:10.5px;line-height:1.5;margin:4px 0;color:#aeb7c5}.cpg-glossary-item p strong{color:#dce2eb}.cpg-glossary-note{margin-bottom:14px;padding:10px 12px;border-left:3px solid var(--purple);background:#8b4cf611;color:#b9c3d1;font-size:10.5px;line-height:1.5}
      @media(max-width:1450px){.cpg-filters{grid-template-columns:180px repeat(5,minmax(120px,1fr)) 125px}.cpg-main{grid-template-columns:minmax(390px,1.1fr) 230px minmax(470px,1.25fr)}.cpg-kpi{padding:10px 8px;gap:7px}.cpg-kpi-icon{width:32px;height:32px}.cpg-kpi-value{font-size:15px}.cpg-table th,.cpg-table td{padding:7px 7px;font-size:8.8px}}
      @media(max-width:1150px){.cpg-filters{grid-template-columns:repeat(4,1fr)}.cpg-clear{margin-top:15px}.cpg-kpis{grid-template-columns:repeat(3,1fr)}.cpg-main{grid-template-columns:1.2fr .7fr;grid-template-rows:430px 220px 220px}.cpg-map-card{grid-row:1;grid-column:1}.cpg-ranks{grid-row:1;grid-column:2}.cpg-city,.cpg-customer{grid-column:1/3}.cpg-bottom{grid-template-columns:1fr 1fr;height:auto}.cpg-bottom>.cpg-card:last-child{grid-column:1/3;height:220px}.cpg-glossary-grid{grid-template-columns:1fr}}
      `; document.head.appendChild(s);
    }
    function icon(name,size=ICON_SIZE_DEFAULT){return `<i data-lucide="${name}" data-cpg-icon aria-hidden="true" style="width:${size}px;height:${size}px"></i>`;}
    function paintIcons(root){if(window.lucide?.createIcons) window.lucide.createIcons({root,attrs:{"stroke-width":String(ICON_STROKE_WIDTH),"stroke-linecap":"round","stroke-linejoin":"round"}});}
    const money=(v)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(Number(v)||0);
    const number=(v,d=0)=>new Intl.NumberFormat("pt-BR",{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number(v)||0);
    const pct=(v)=>`${number((Number(v)||0)*100,1)}%`;
    const date=(v)=>v?new Intl.DateTimeFormat("pt-BR").format(new Date(`${String(v).slice(0,10)}T12:00:00`)):"—";
    const periodLabel=()=>filters.periodMode==="mes"?"Mês atual":filters.periodMode==="ytd"?"YTD":"Ano";
    const currentKey=()=>[year,month,filters.periodMode,filters.seller,filters.state,filters.city,filters.customerId,filters.sku].join("|");
    function payload(){return {p_org:null,p_year:year,p_month:month,p_period:filters.periodMode,p_seller:filters.seller,p_state:filters.state||null,p_city:filters.city||null,p_customer_id:filters.customerId||null,p_sku:filters.sku||null};}

    async function load(force=false){
      const key=currentKey(); if(!force&&key===loadedKey&&data)return;
      loading=true;error="";render(host);
      try{const p=payload();p.p_org=await resolveOrganizationId();data=await callSupabaseRpc("comercial_pecas_geo_performance",p);loadedKey=key;}
      catch(e){console.error(e);error="Não foi possível carregar a performance geográfica de peças.";}
      finally{loading=false;render(host);}
    }
    function syncPeriod(){year=Number(state.currentPeriod?.year||year);month=Number(state.currentPeriod?.month||month);}
    function delta(cur,prev){if(!(Number(prev)>0))return `<span class="cpg-delta">sem base comparável</span>`;const d=(Number(cur)-Number(prev))/Number(prev),pos=d>=0;return `<span class="cpg-delta ${pos?"pos":"neg"}">vs período ant. ${pos?"▲":"▼"} ${pct(Math.abs(d))}</span>`;}
    function kpi(iconName,label,value,cur,prev,warning=""){return `<div class="cpg-kpi"><span class="cpg-kpi-icon">${icon(iconName,ICON_SIZE_KPI)}</span><div style="min-width:0"><div class="cpg-kpi-label">${label}</div><div class="cpg-kpi-value">${value}</div>${warning||delta(cur,prev)}</div></div>`;}
    function renderKpis(){const k=data?.kpis||{},p=k.previous||{};const terr=`${number(Math.max(0,(k.territories||0)-(k.hasExterior?1:0)))}${k.hasExterior?" + EX":""}`;return `<div class="cpg-kpis">
      ${kpi("circle-dollar-sign","Faturamento Peças",money(k.revenue),k.revenue,p.revenue)}
      ${kpi("users","Clientes compradores",number(k.customers),k.customers,p.customers)}
      ${kpi("file-text","Notas fiscais",number(k.invoices),k.invoices,p.invoices,!data.documentsReliable?`<span class="cpg-delta cpg-warning" title="A carga histórica não possui documento/série em todas as linhas">base documental parcial</span>`:"")}
      ${kpi("circle-dollar-sign","Fat. médio por cliente",money(k.revenuePerCustomer),k.revenuePerCustomer,p.revenuePerCustomer)}
      ${kpi("shopping-cart","Compras por cliente",number(k.purchasesPerCustomer,2),k.purchasesPerCustomer,p.purchasesPerCustomer)}
      ${kpi("map","Territórios atendidos",terr,k.territories,p.territories)}
    </div>`;}
    function metricValue(r,metric=filters.mapMetric){return Number(metric==="revenue"?r.revenue:metric==="customers"?r.customers:r.purchasesPerCustomer)||0;}
    function heat(value,max){if(!value)return "#282d37";const t=Math.max(.12,Math.min(1,value/(max||1)));const a=[45,25,77],b=[157,103,235],rgb=a.map((v,i)=>Math.round(v+(b[i]-v)*t));return `rgb(${rgb.join(",")})`;}
    function mapHtml(){const rows=(data?.map||[]),by=Object.fromEntries(rows.map(r=>[r.territory,r])),max=Math.max(0,...rows.filter(r=>r.territory!=="EX").map(metricValue));const states=BR.states.map(st=>{const r=by[st.uf],val=r?metricValue(r):0;return `<path class="cpg-state ${filters.state===st.uf?"selected":""}" data-map-uf="${st.uf}" d="${statePath(st.rings)}" fill="${heat(val,max)}"><title>${escapeHtml(st.nome)}</title></path>`;}).join("");const ex=by.EX;const metricTitle=filters.mapMetric==="revenue"?"FATURAMENTO (R$)":filters.mapMetric==="customers"?"CLIENTES":"COMPRAS / CLIENTE";return `<div class="cpg-card cpg-map-card"><div class="cpg-map-head"><div class="cpg-card-head" style="padding:0;border:0;height:auto"><div><h2>MAPA DO BRASIL</h2><p>Selecione a métrica para visualizar no mapa</p></div></div><div class="cpg-metric"><button data-metric="revenue" class="${filters.mapMetric==="revenue"?"active":""}">Faturamento</button><button data-metric="customers" class="${filters.mapMetric==="customers"?"active":""}">Clientes</button><button data-metric="recurrence" class="${filters.mapMetric==="recurrence"?"active":""}">Recorrência</button></div></div><div class="cpg-map-area ${filters.state==="EX"?"ex-selected":""}"><svg class="map" viewBox="0 0 ${VW} ${VH}" role="img" aria-label="Mapa do Brasil por UF">${states}</svg><div class="cpg-legend"><strong>${metricTitle}</strong>${[1,.75,.5,.25,0].map((t,i)=>`<span><i style="background:${heat(t||0,max?1:0)}"></i>${i===0?"Maior intensidade":i===4?"Sem vendas":"Faixa "+(5-i)}</span>`).join("")}</div><button class="cpg-ex ${filters.state==="EX"?"active":""}" data-map-uf="EX"><strong>EX</strong><span>${ex?money(ex.revenue):"Sem vendas"}</span></button></div></div>`;}
    function rankCard(title,iconName,key,shareKey){const arr=[...(data?.map||[])].filter(r=>metricValue(r,key)>0).sort((a,b)=>metricValue(b,key)-metricValue(a,key)).slice(0,5),max=arr.length?metricValue(arr[0],key):1;return `<div class="cpg-card cpg-rank"><h3>${icon(iconName,14)}${title}</h3>${arr.map((r,i)=>`<div class="cpg-rank-row" data-rank-uf="${r.territory}"><span class="pos">${i+1}</span><b>${r.territory}</b><div class="cpg-barline"><div class="cpg-bar"><i style="width:${metricValue(r,key)/max*100}%"></i></div><b>${key==="revenue"?money(r.revenue):key==="customers"?number(r.customers):number(r.purchasesPerCustomer,2)}</b></div><span class="pct">${shareKey?pct(r[shareKey]):""}</span></div>`).join("")||`<div style="color:var(--muted);padding:18px 0">Sem dados</div>`}</div>`;}
    function ranksHtml(){return `<div class="cpg-ranks">${rankCard("Ranking por faturamento","circle-dollar-sign","revenue","revenueShare")}${rankCard("Ranking por clientes","users","customers","customerShare")}${rankCard("Ranking por recorrência","shopping-cart","recurrence",null)}</div>`;}
    function cardTitle(iconName,title,key){return `<div class="cpg-card-head"><h2>${icon(iconName,14)}${title}</h2><button class="cpg-more" data-expand="${key}">${expanded[key]?"Ver top 5":"Ver todos"}</button></div>`;}
    function citiesHtml(){const arr=(data?.topCities||[]).slice(0,expanded.cities?50:5),title=`TOP MUNICÍPIOS${filters.state&&filters.state!=="EX"?` (${filters.state})`:""}`;return `<div class="cpg-card cpg-city">${cardTitle("map-pin",title,"cities")}<div class="cpg-table-wrap"><table class="cpg-table"><thead><tr><th>Município</th><th>UF</th><th class="num">Clientes</th><th class="num">Faturamento</th><th class="num">%</th><th class="num">NFs</th><th class="num">Fat. médio/cliente</th></tr></thead><tbody>${arr.map(r=>`<tr><td>${escapeHtml(r.city||"—")}</td><td>${r.territory}</td><td class="num">${number(r.customers)}</td><td class="num">${money(r.revenue)}</td><td class="num">${pct(r.share)}</td><td class="num">${number(r.invoices)}</td><td class="num">${money(r.revenuePerCustomer)}</td></tr>`).join("")||`<tr><td colspan="7">${filters.state==="EX"?"Municípios não disponíveis para EX.":"Sem dados."}</td></tr>`}</tbody></table></div></div>`;}
    function customersHtml(){const arr=(data?.topCustomers||[]).slice(0,expanded.customers?50:5),title=`TOP CLIENTES${filters.state?` (${filters.state})`:""}`;return `<div class="cpg-card cpg-customer">${cardTitle("users",title,"customers")}<div class="cpg-table-wrap"><table class="cpg-table"><thead><tr><th>Cliente</th><th>Município</th><th class="num">Faturamento</th><th class="num">NFs</th><th class="num">Compras</th><th class="num">Última compra</th><th class="num">Dias sem comprar</th></tr></thead><tbody>${arr.map(r=>`<tr><td title="${escapeHtml(`${r.code} — ${r.name}`)}">${escapeHtml(r.name)}</td><td>${escapeHtml(r.city||r.territory||"—")}</td><td class="num">${money(r.revenue)}</td><td class="num">${number(r.invoices)}</td><td class="num">${number(r.purchases)}</td><td class="num">${date(r.lastPurchase)}</td><td class="num">${number(r.daysWithoutPurchase)}</td></tr>`).join("")||`<tr><td colspan="7">Sem dados.</td></tr>`}</tbody></table></div></div>`;}
    const DONUT_COLORS=["#5d24ba","#7131ce","#8849dc","#9d67e7","#b184ee","#c7a3f4"];
    function distributionHtml(title,rows,recurrence=false){let at=0;const stops=rows.map((r,i)=>{const start=at;at+=Number(r.share||0)*360;return `${DONUT_COLORS[i%6]} ${start}deg ${at}deg`;}).join(",");const recurring=Number(data?.recurringCustomers||0),total=Number(data?.kpis?.customers||0);return `<div class="cpg-card"><div class="cpg-card-head"><h2>${title}</h2></div><div class="cpg-dist"><div class="cpg-donut" style="background:conic-gradient(${stops||"#292e38 0 360deg"})"></div><div>${rows.map((r,i)=>`<div class="cpg-dist-row"><span><i class="dot" style="background:${DONUT_COLORS[i%6]}"></i>${escapeHtml(r.range)}</span><b>${number(r.customers)}</b><em>${pct(r.share)}</em></div>`).join("")}</div>${recurrence?`<div class="cpg-dist-foot"><span>Clientes recorrentes (≥ 2 compras)</span><b>${number(recurring)} · ${pct(total?recurring/total:0)}</b></div>`:`<div class="cpg-dist-foot"><span>Total</span><b>${number(total)} · 100%</b></div>`}</div></div>`;}
    function skusHtml(){const arr=(data?.topSkus||[]).slice(0,expanded.skus?50:5);return `<div class="cpg-card">${cardTitle("box","TOP SKUs","skus")}<div class="cpg-table-wrap"><table class="cpg-table"><thead><tr><th>SKU</th><th>Descrição</th><th class="num">Qtd. vendida</th><th class="num">Faturamento</th><th class="num">%</th><th class="num">Clientes</th><th class="num">UFs</th><th class="num">Municípios</th></tr></thead><tbody>${arr.map(r=>`<tr class="clickable" data-sku="${escapeHtml(r.sku)}" data-sku-label="${escapeHtml(`${r.sku} — ${r.description}`)}"><td>${escapeHtml(r.sku)}</td><td>${escapeHtml(r.description)}</td><td class="num">${number(r.quantity)}</td><td class="num">${money(r.revenue)}</td><td class="num">${pct(r.share)}</td><td class="num">${number(r.customers)}</td><td class="num">${number(r.territories)}</td><td class="num">${number(r.municipalities)}</td></tr>`).join("")||`<tr><td colspan="8">Sem dados.</td></tr>`}</tbody></table></div></div>`;}
    function filterBar(){const cityDisabled=filters.state==="EX";return `<div class="cpg-filters"><div class="cpg-field"><label>Período</label><div class="cpg-period">${[["mes","MÊS"],["ytd","YTD"],["fy","ANO"]].map(([v,l])=>`<button data-period="${v}" class="${filters.periodMode===v?"active":""}">${l}</button>`).join("")}</div></div><div class="cpg-field"><label>Vendedor</label><select class="cpg-control" data-filter="seller"><option value="all">Todos</option><option value="jenifer" ${filters.seller==="jenifer"?"selected":""}>Jenifer</option><option value="others" ${filters.seller==="others"?"selected":""}>Outros</option></select></div><div class="cpg-field"><label>UF</label><select class="cpg-control" data-filter="state"><option value="">Todos</option>${UFS.map(u=>`<option value="${u}" ${filters.state===u?"selected":""}>${u}${u==="EX"?" — Exterior":""}</option>`).join("")}</select></div><div class="cpg-field"><label>Município</label><select class="cpg-control" data-filter="city" ${cityDisabled?"disabled":""}><option value="">${cityDisabled?"Indisponível para EX":"Todos"}</option>${(data?.cities||[]).map(c=>`<option value="${escapeHtml(c)}" ${filters.city===c?"selected":""}>${escapeHtml(c)}</option>`).join("")}</select></div>${searchField("customer","Cliente",filters.customerLabel||"Todos os clientes")}${searchField("sku","SKU",filters.skuLabel||"Todos os SKUs")}<button class="cpg-clear" data-clear>${icon("funnel-x",14)}LIMPAR FILTROS</button></div>`;}
    function searchField(kind,label,value){return `<div class="cpg-field"><label>${label}</label><div class="cpg-search-wrap"><input class="cpg-control" data-search="${kind}" value="${escapeHtml(value)}" autocomplete="off" aria-label="Buscar ${label}">${icon("search",14)}</div><div class="cpg-suggest" data-suggestions="${kind}" hidden></div></div>`;}
    function compliance(){const seller=filters.seller==="all"?"Todos":filters.seller==="jenifer"?"Jenifer":"Outros";return `<div class="cpg-compliance"><span>${icon("info",14)}Os valores apresentados seguem exatamente a mesma regra de apuração de Peças do Painel de Vendas.</span><span>Critérios aplicados: Período: ${periodLabel()} | Vendedor: ${seller} | UF: ${filters.state||"Todos"} | Município: ${filters.city||"Todos"} | Cliente: ${filters.customerLabel||"Todos"} | SKU: ${filters.sku||"Todos"}</span></div>`;}
    function glossaryHtml(){return `<div class="cpg-glossary-backdrop" data-glossary-backdrop><section class="cpg-glossary" role="dialog" aria-modal="true" aria-labelledby="cpg-glossary-title"><header class="cpg-glossary-head"><div><h2 id="cpg-glossary-title">${icon("book-open",18)}Como interpretar este relatório</h2><p>Dicionário de métricas, fórmulas e leituras recomendadas.</p></div><button class="cpg-glossary-close" data-glossary-close aria-label="Fechar dicionário">${icon("x",16)}</button></header><div class="cpg-glossary-body"><div class="cpg-glossary-note"><strong>Regra central:</strong> todos os indicadores respondem aos filtros ativos. Percentuais, médias e rankings sempre são recalculados sobre o universo atualmente selecionado.</div><div class="cpg-glossary-grid">${GLOSSARY.map(item=>`<article class="cpg-glossary-item"><span class="cpg-glossary-group">${escapeHtml(item.group)}</span><h3>${escapeHtml(item.title)}</h3><p><strong>Como é calculado:</strong> ${escapeHtml(item.formula)}</p><p><strong>Como interpretar:</strong> ${escapeHtml(item.read)}</p></article>`).join("")}</div></div></section></div>`;}
    function render(container){if(!container)return;ensureStyle();host=container;if(!isSupabaseConfigured()){container.innerHTML=`<div class="cpg-empty">Configuração do Supabase ausente.</div>`;return;}const updated=data?.updatedAt?new Date(data.updatedAt).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"—";if(error&&!data){container.innerHTML=`<div class="cpg-empty">${escapeHtml(error)}<br><button class="cpg-more" data-retry>Tentar novamente</button></div>`;bind(container);return;}container.innerHTML=`<div class="cpg ${loading?"cpg-skeleton":""}"><div class="cpg-header"><div class="cpg-title"><h1>PERFORMANCE GEOGRÁFICA DE PEÇAS</h1><p>Análise da distribuição nacional de vendas de peças</p></div><div class="cpg-meta"><p>Última atualização: ${updated}</p><button class="cpg-help" data-glossary-open>${icon("book-open",14)}Como interpretar</button></div></div>${filterBar()}${data?.kpis?`${renderKpis()}${(Number(data.kpis.revenue)||0)===0?`<div class="cpg-empty">Nenhuma venda encontrada para os filtros selecionados.</div>`:`<div class="cpg-main">${mapHtml()}${ranksHtml()}${filters.state==="EX"?`<div class="cpg-card cpg-city"><div class="cpg-card-head"><h2>${icon("map-pin",14)}TOP MUNICÍPIOS</h2></div><div class="cpg-empty" style="border:0;padding:55px 15px">Municípios não disponíveis para EX.</div></div>`:citiesHtml()}${customersHtml()}</div><div class="cpg-bottom">${distributionHtml("DISTRIBUIÇÃO DOS CLIENTES POR FAIXA DE FATURAMENTO",data.revenueDistribution||[])}${distributionHtml("DISTRIBUIÇÃO POR RECORRÊNCIA (COMPRAS NO PERÍODO)",data.recurrenceDistribution||[],true)}${skusHtml()}</div>`}${compliance()}`:`<div class="cpg-empty">Carregando dados…</div>`}</div>`;if(showGlossary)container.querySelector(".cpg")?.insertAdjacentHTML("beforeend",glossaryHtml());bind(container);paintIcons(container);}

    function showTooltip(e,uf){const r=(data?.map||[]).find(x=>x.territory===uf);if(!tooltip){tooltip=document.createElement("div");tooltip.className="cpg-tt";document.body.appendChild(tooltip);}tooltip.hidden=false;tooltip.innerHTML=r?`<strong>${escapeHtml(STATE_NAMES[uf]||uf)} (${uf})</strong><div class="row"><span>Faturamento</span><b>${money(r.revenue)}</b></div><div class="row"><span>% do total</span><b>${pct(r.revenueShare)}</b></div><div class="row"><span>Clientes</span><b>${number(r.customers)}</b></div><div class="row"><span>% da base</span><b>${pct(r.customerShare)}</b></div><div class="row"><span>NFs</span><b>${number(r.invoices)}</b></div><div class="row"><span>Fat. médio/cliente</span><b>${money(r.revenuePerCustomer)}</b></div><div class="row"><span>Compras/cliente</span><b>${number(r.purchasesPerCustomer,2)}</b></div>`:`<strong>${escapeHtml(STATE_NAMES[uf]||uf)} (${uf})</strong>Sem vendas no período.`;tooltip.style.left=Math.min(e.clientX+14,window.innerWidth-245)+"px";tooltip.style.top=Math.min(e.clientY+14,window.innerHeight-210)+"px";}
    function hideTooltip(){if(tooltip)tooltip.hidden=true;}
    async function searchOptions(kind,q,box){try{const org=await resolveOrganizationId(),rows=await callSupabaseRpc("comercial_pecas_geo_options",{p_org:org,p_kind:kind,p_search:q,p_state:filters.state&&filters.state!=="EX"?filters.state:null,p_limit:20});box.innerHTML=(rows||[]).map(r=>`<button data-option-kind="${kind}" data-option-id="${escapeHtml(r.id)}" data-option-label="${escapeHtml(r.label)}">${escapeHtml(r.label)}</button>`).join("")||`<div class="empty">Nenhum resultado</div>`;box.hidden=false;}catch(e){console.error(e);box.innerHTML=`<div class="empty">Não foi possível pesquisar.</div>`;box.hidden=false;}}
    function setState(uf){filters.state=filters.state===uf?"":uf;filters.city="";filters.customerId="";filters.customerLabel="";expanded={cities:false,customers:false,skus:false};load();}
    function bind(container){
      container.querySelector("[data-retry]")?.addEventListener("click",()=>load(true));
      container.querySelector("[data-glossary-open]")?.addEventListener("click",()=>{showGlossary=true;render(container);});
      container.querySelector("[data-glossary-close]")?.addEventListener("click",()=>{showGlossary=false;render(container);});
      container.querySelector("[data-glossary-backdrop]")?.addEventListener("click",e=>{if(e.target===e.currentTarget){showGlossary=false;render(container);}});
      container.querySelectorAll("[data-period]").forEach(b=>b.addEventListener("click",()=>{filters.periodMode=b.dataset.period;load();}));
      container.querySelectorAll("[data-filter]").forEach(el=>el.addEventListener("change",()=>{filters[el.dataset.filter]=el.value;if(el.dataset.filter==="state"){filters.city="";filters.customerId="";filters.customerLabel="";}load();}));
      container.querySelector("[data-clear]")?.addEventListener("click",()=>{filters={...filters,seller:"all",state:"",city:"",customerId:"",customerLabel:"",sku:"",skuLabel:"",mapMetric:"revenue"};expanded={cities:false,customers:false,skus:false};load();});
      container.querySelectorAll("[data-metric]").forEach(b=>b.addEventListener("click",()=>{filters.mapMetric=b.dataset.metric;render(container);}));
      container.querySelectorAll("[data-map-uf],[data-rank-uf]").forEach(el=>{const uf=el.dataset.mapUf||el.dataset.rankUf;el.addEventListener("click",()=>setState(uf));el.addEventListener("mousemove",e=>showTooltip(e,uf));el.addEventListener("mouseleave",hideTooltip);});
      container.querySelectorAll("[data-expand]").forEach(b=>b.addEventListener("click",()=>{expanded[b.dataset.expand]=!expanded[b.dataset.expand];render(container);}));
      container.querySelectorAll("tr[data-sku]").forEach(tr=>tr.addEventListener("click",()=>{filters.sku=tr.dataset.sku;filters.skuLabel=tr.dataset.skuLabel;load();}));
      container.querySelectorAll("[data-search]").forEach(input=>{const kind=input.dataset.search,box=container.querySelector(`[data-suggestions="${kind}"]`);input.addEventListener("focus",()=>{if(!input.value.startsWith("Todos"))searchOptions(kind,input.value,box);});input.addEventListener("input",()=>{clearTimeout(searchTimer);if(kind==="customer"){filters.customerId="";filters.customerLabel="";}else{filters.sku="";filters.skuLabel="";}searchTimer=setTimeout(()=>searchOptions(kind,input.value,box),300);});});
      container.querySelectorAll("[data-suggestions]").forEach(box=>box.addEventListener("click",e=>{const b=e.target.closest("button[data-option-kind]");if(!b)return;const kind=b.dataset.optionKind;if(kind==="customer"){filters.customerId=b.dataset.optionId;filters.customerLabel=b.dataset.optionLabel;}else{filters.sku=b.dataset.optionId;filters.skuLabel=b.dataset.optionLabel;}box.hidden=true;load();}));
      if(!docCloseBound){docCloseBound=true;document.addEventListener("click",(e)=>{if(host&&document.body.contains(host)&&!e.target.closest(".cpg-search-wrap")&&!e.target.closest(".cpg-suggest"))host.querySelectorAll(".cpg-suggest").forEach(x=>x.hidden=true);});}
      if(!glossaryKeyBound){glossaryKeyBound=true;document.addEventListener("keydown",e=>{if(e.key==="Escape"&&showGlossary&&host){showGlossary=false;render(host);}});}
    }
    function renderSelectedPecasGeo(container,reportId){if(reportId!==REPORT_ID)return false;syncPeriod();host=container;hideTooltip();if(data&&loadedKey===currentKey())render(container);else load();return true;}
    return { renderSelectedPecasGeo, REPORT_ID };
  }
  window.VECTON_COMERCIAL_PECAS_GEO={createComercialPecasGeoModule};
})(window);
