const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const values = new Map();
const context = { document: { documentElement: { dataset: {} } }, window: { localStorage: { getItem: k => values.get(k), setItem: (k,v) => values.set(k,v) } } };
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../src/core/appearance.js'),'utf8'), context);
const theme=context.window.VECTON_APPEARANCE;
assert.equal(theme.get(),'dark');
assert.equal(theme.save('clear'),false);
theme.setUser('alice'); theme.preview('clear'); theme.restore(); assert.equal(theme.get(),'dark');
assert.equal(theme.save('clear'),true);
theme.setUser('bob'); assert.equal(theme.get(),'dark');
theme.setUser('alice'); assert.equal(theme.get(),'clear');
theme.setUser(null); assert.equal(theme.get(),'dark');
values.set('vecton.appearance.v1.bob','invalid'); theme.setUser('bob'); assert.equal(theme.get(),'dark');
context.window.localStorage.setItem=()=>{throw Error('quota');};
theme.preview('clear'); assert.equal(theme.save('clear'),false); theme.restore(); assert.equal(theme.get(),'dark');
context.window.localStorage.getItem=()=>{throw Error('blocked');}; theme.setUser('alice'); assert.equal(theme.get(),'dark');
console.log('Appearance: default, persistence, user isolation, logout, cancel and storage failure passed');
