const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { PGlite } = require(process.env.FC_PGLITE_TEST_LIB || '@electric-sql/pglite');
const org = '10000000-0000-4000-8000-000000000001', otherOrg = '10000000-0000-4000-8000-000000000002';
const admin = '20000000-0000-4000-8000-000000000001', analyst = '20000000-0000-4000-8000-000000000002';
(async () => {
  const db = new PGlite();
  try {
    await db.exec(`create role authenticated; create schema auth;
      create table auth.users(id uuid primary key);
      create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.user',true),'')::uuid$$;
      create table public.organizations(id uuid primary key);
      create table public.user_profiles(organization_id uuid,user_id uuid,is_active boolean,access_role text,additional_access_roles text[] default '{}',extra_report_ids text[] default '{}');
      create function public.is_org_member(target uuid) returns boolean language sql stable security definer as $$select exists(select 1 from user_profiles where organization_id=target and user_id=auth.uid() and is_active)$$;
      insert into auth.users values('${admin}'),('${analyst}'); insert into organizations values('${org}'),('${otherOrg}');
      insert into user_profiles(organization_id,user_id,is_active,access_role) values('${org}','${admin}',true,'admin'),('${org}','${analyst}',true,'analyst');
      select set_config('test.user','${admin}',false);`);
    for (const file of ['219_fc_chart_of_accounts.sql','221_fc_annual_import.sql','222_fc_scenarios.sql']) await db.exec(fs.readFileSync(path.join(__dirname,'../supabase',file),'utf8'));
    await db.exec(`
      alter table user_profiles add column full_name text;
      create table notification_event_types(kind text primary key,label text,description text,target_report_id text,sort_order int,trigger_mode text);
      create table notification_settings(organization_id uuid,kind text,is_active boolean default true,in_app boolean default true,email boolean default false,email_recipients text[] default '{}',messenger boolean default false,messenger_recipients uuid[] default '{}',primary key(organization_id,kind));
      create table notifications(id uuid primary key default gen_random_uuid(),organization_id uuid,kind text,title text,body text,ref_year int,ref_month int,target_report_id text,actor_user_id uuid);
      create table notification_email_outbox(notification_id uuid,organization_id uuid,recipients text[],subject text,body_text text,link_path text);
      create table messenger_test(organization_id uuid,title text,body text,recipients uuid[]);
      create function notify_via_messenger(org uuid,title text,body text,recipients uuid[]) returns void language sql as $$insert into messenger_test values(org,title,body,recipients)$$;
    `);
    await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/226_fc_load_notifications.sql'),'utf8'));
    await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/227_fc_notification_label.sql'),'utf8'));
    const context = async year => (await db.query('select fc_import_context($1,$2) as value',[org,year])).rows[0].value;
    const apply = payload => db.query('select apply_fc_annual_import($1,$2::jsonb) as value',[org,JSON.stringify(payload)]);
    const uuid = () => require('node:crypto').randomUUID();
    function payload(ctx,year=2024) {
      return { id:uuid(),year,expected_batch_id:ctx.batch?.id||null,plan_version:ctx.plan_version,file_name:'nome-livre.xlsx',file_size:3,file_base64:'YWJj',
        scenarios:Array(12).fill('Real'),quantities:Array(12).fill(1),opening_mode:'closing_january',opening_value:100000,
        entries:ctx.plan.filter(n=>n.node_class==='Analitica').map(n=>({account_id:n.id,amounts:Array(12).fill(n.active?10:0)})) };
    }
    let ctx = await context(2024), first = payload(ctx);
    await apply(first); await apply(first);
    assert.equal((await db.query('select count(*)::int as n from notifications')).rows[0].n,1,'retry does not duplicate notification'); // retry idempotente
    assert.equal((await db.query('select count(*)::int as n from fc_import_batches')).rows[0].n,1);
    assert.equal((await db.query('select opening_balance::float8 as n from fc_import_batches')).rows[0].n,99240);
    assert.equal((await db.query('select title from notifications limit 1')).rows[0].title,'Carga de Fluxo de Caixa (realizado) aplicada');
    const invalid = payload(await context(2024)); invalid.entries[0].amounts.pop();
    await assert.rejects(apply(invalid),/12 meses/);
    assert.equal((await context(2024)).batch.id,first.id);
    const future = payload(await context(2100),2100); await assert.rejects(apply(future),/futura/);
    const cross = payload(await context(2024)); cross.entries[0].account_id = (await db.query("select id from fc_plan_nodes where organization_id=$1 and node_class='Analitica' limit 1",[otherOrg])).rows[0].id;
    await assert.rejects(apply(cross),/outra empresa/);
    const duplicates = payload(await context(2024)); duplicates.entries[0].account_id = duplicates.entries[1].account_id; await assert.rejects(apply(duplicates),/duplicada/);
    const second = payload(await context(2024)); second.entries[0].amounts[11]=1234; second.scenarios=Array.from({length:12},(_,i)=>i<8?'Real':'Fcst');
    await apply(second);
    for (const table of ['fc_import_batches','fc_import_values','fc_import_files','fc_import_events']) {
      const column = table==='fc_import_batches'?'id':'batch_id';
      assert.equal((await db.query(`select count(*)::int as n from ${table} where ${column}=$1`,[first.id])).rows[0].n,0,`${table}: anterior excluído`);
    }
    await assert.rejects(apply({ ...first,id:uuid() }),/mudou durante/);
    // Ano diferente preservado.
    const different = payload(await context(2023),2023); await apply(different);
    assert.equal((await db.query('select count(*)::int as n from fc_import_batches')).rows[0].n,2);
    const outdated = payload(await context(2024));
    await db.query("update fc_plan_nodes set name=name || ' revisada' where id=$1",[outdated.entries[0].account_id]);
    await assert.rejects(apply(outdated),/Plano de Contas FC mudou/);
    // Falha após o DELETE também reverte arquivo, valores e auditoria anteriores.
    const rollback = payload(await context(2024)); rollback.file_name='x'.repeat(256)+'.xlsx';
    await assert.rejects(apply(rollback),/check constraint/);
    assert.equal((await context(2024)).batch.id,second.id);
    assert.equal((await db.query('select count(*)::int as n from fc_import_files where batch_id=$1',[second.id])).rows[0].n,1);
    const scenarioPayload={name:'Simulação teste',base_batch_id:second.id,movements:Object.fromEntries(second.entries.map(e=>[e.account_id,[...e.amounts]])),quantities:[...second.quantities]};
    scenarioPayload.movements[second.entries[0].account_id][9]=4321;
    const saveScenario=p=>db.query('select save_fc_scenario($1,$2::jsonb) as id',[org,JSON.stringify(p)]);
    const scenarioId=(await saveScenario(scenarioPayload)).rows[0].id;
    assert.equal((await db.query('select report_data from fc_scenarios where id=$1',[scenarioId])).rows[0].report_data.movements[second.entries[0].account_id][9],4321);
    const bad=JSON.parse(JSON.stringify(scenarioPayload));bad.movements[second.entries[0].account_id][0]=999;
    await assert.rejects(saveScenario(bad),/Real/);
    const badQuantity=JSON.parse(JSON.stringify(scenarioPayload));badQuantity.quantities[0]=5;
    await assert.rejects(saveScenario(badQuantity),/Real/);
    badQuantity.quantities[0]=1;badQuantity.quantities[9]=-1;
    await assert.rejects(saveScenario(badQuantity),/Quantidade/);
    const official=(await db.query('select amounts from fc_import_values where batch_id=$1 and account_id=$2',[second.id,second.entries[0].account_id])).rows[0].amounts;
    assert.equal(Number(official[9]),10);
    await db.exec('begin');await db.query('delete from fc_import_batches where id=$1',[second.id]);
    assert.equal((await db.query('select count(*)::int as n from fc_scenarios where id=$1',[scenarioId])).rows[0].n,1);
    await saveScenario({...scenarioPayload,base_batch_id:null,source_scenario_id:scenarioId,name:'Cópia após substituição'});
    await db.exec('rollback');
    const denied = payload(await context(2024));
    await db.exec(`select set_config('test.user','${analyst}',false); set role authenticated;`);
    await assert.rejects(apply(denied),/Sem permissão/);
    assert.equal((await db.query('select count(*)::int as n from fc_import_batches')).rows[0].n,0);
    await db.exec(`reset role; update user_profiles set extra_report_ids=array['cashFlow'] where user_id='${analyst}'; set role authenticated;`);
    assert.equal((await db.query('select count(*)::int as n from fc_import_batches')).rows[0].n,2);
    await assert.rejects(apply(denied),/Sem permissão/);
    assert.equal((await db.query('select count(*)::int as n from fc_scenarios')).rows[0].n,0);
    await assert.rejects(saveScenario({...scenarioPayload,source_scenario_id:scenarioId}),/não encontrado/);
    await db.exec('reset role');
    await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/223_fc_shared_scenarios.sql'),'utf8'));
    await db.exec('set role authenticated');
    assert.equal((await db.query('select count(*)::int as n from fc_scenarios')).rows[0].n,1,'admin scenario is visible to authorized analyst');
    const personalId=(await saveScenario({...scenarioPayload,source_scenario_id:scenarioId,is_shared:true,name:'Pessoal'})).rows[0].id;
    assert.equal((await db.query('select is_shared from fc_scenarios where id=$1',[personalId])).rows[0].is_shared,false,'client cannot force sharing');
    await db.exec(`reset role;select set_config('test.user','${admin}',false);set role authenticated;`);
    assert.equal((await db.query('select count(*)::int as n from fc_scenarios where id=$1',[personalId])).rows[0].n,0,'personal scenario remains private');
    await assert.rejects(saveScenario({...scenarioPayload,source_scenario_id:personalId}),/não encontrado/);
    const sharedId=(await saveScenario({...scenarioPayload,source_scenario_id:scenarioId,name:'Admin compartilhado'})).rows[0].id;
    assert.equal((await db.query('select is_shared from fc_scenarios where id=$1',[sharedId])).rows[0].is_shared,true);
    await db.exec(`reset role;update user_profiles set access_role='super_admin' where user_id='${admin}';set role authenticated;`);
    const superId=(await saveScenario({...scenarioPayload,source_scenario_id:scenarioId,name:'Super admin'})).rows[0].id;
    assert.equal((await db.query('select is_shared from fc_scenarios where id=$1',[superId])).rows[0].is_shared,true);
    await db.exec(`reset role;update user_profiles set access_role='analyst',additional_access_roles=array['admin'] where user_id='${admin}';set role authenticated;`);
    const extraId=(await saveScenario({...scenarioPayload,source_scenario_id:scenarioId,name:'Perfil adicional'})).rows[0].id;
    assert.equal((await db.query('select is_shared from fc_scenarios where id=$1',[extraId])).rows[0].is_shared,true);
    await db.exec(`reset role;select set_config('test.user','${analyst}',false);update user_profiles set extra_report_ids='{}' where user_id='${analyst}';set role authenticated;`);
    assert.equal((await db.query('select count(*)::int as n from fc_scenarios')).rows[0].n,0,'access to FC still required');
    await assert.rejects(saveScenario({...scenarioPayload,source_scenario_id:scenarioId}),/Sem permissão/);
    await db.exec(`reset role;select set_config('test.user','${admin}',false);`);
    await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/224_fc_scenario_name_limit.sql'),'utf8'));
    await db.exec('set role authenticated');
    await saveScenario({...scenarioPayload,source_scenario_id:scenarioId,name:'123456789012345'});
    await assert.rejects(saveScenario({...scenarioPayload,source_scenario_id:scenarioId,name:'1234567890123456'}),/15 caracteres/);
    await db.exec('reset role');
    await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/225_fc_delete_scenario.sql'),'utf8'));
    await db.exec('set role authenticated');
    const remove=id=>db.query('select delete_fc_scenario($1,$2)',[org,id]);
    await assert.rejects(remove(personalId),/sem permissão/);
    await assert.rejects(db.query('select delete_fc_scenario($1,$2)',[otherOrg,sharedId]),/Sem permissão/);
    await db.exec(`reset role;update user_profiles set extra_report_ids=array['cashFlow'] where user_id='${analyst}';select set_config('test.user','${analyst}',false);set role authenticated;`);
    await assert.rejects(remove(sharedId),/sem permissão/);
    await remove(personalId);
    assert.equal((await db.query('select count(*)::int as n from fc_scenarios where id=$1',[personalId])).rows[0].n,0);
    await db.exec(`reset role;update user_profiles set additional_access_roles=array['super_admin'] where user_id='${analyst}';set role authenticated;`);
    await remove(sharedId);
    assert.equal((await db.query('select count(*)::int as n from fc_scenarios where id=$1',[sharedId])).rows[0].n,0);
    assert.equal((await db.query('select count(*)::int as n from fc_import_batches')).rows[0].n,2);
    await db.exec(`reset role;select set_config('test.user','${admin}',false);`);
    const countNotices=async()=>Number((await db.query('select count(*) as n from notifications')).rows[0].n);
    const before=await countNotices();
    await db.query("update notification_settings set is_active=false where organization_id=$1",[org]);
    await apply(payload(await context(2022),2022));assert.equal(await countNotices(),before);
    await db.query("update notification_settings set is_active=true,in_app=false,email=true,email_recipients=array['test@example.invalid'],messenger=true,messenger_recipients=array[$2::uuid] where organization_id=$1",[org,admin]);
    const noticeBatch=payload(await context(2022),2022);await apply(noticeBatch);await apply(noticeBatch);
    assert.equal(await countNotices(),before);
    assert.equal((await db.query('select count(*)::int as n from notification_email_outbox')).rows[0].n,1);
    assert.equal((await db.query('select count(*)::int as n from messenger_test')).rows[0].n,1);
    assert.match((await db.query('select link_path from notification_email_outbox')).rows[0].link_path,/report=cashFlow&ano=2022&mes=12/);
    const broken=payload(await context(2022),2022);broken.entries[0].amounts=[];
    await assert.rejects(apply(broken));
    assert.equal((await db.query('select count(*)::int as n from notification_email_outbox')).rows[0].n,1);
    console.log('FC notifications: default bell, inactive switch, channel independence, recipients, annual link, retry and validation failure passed.');
    console.log('FC deletion: owner, shared admin, private isolation, organization and official batch preservation passed.');
    console.log('FC shared scenarios: admin/super/additional roles, personal copies, visibility and denied access passed.');
    console.log('FC SQL: scenarios, Real protection, base isolation, snapshot survival, private access; migrations, annual replacement, file/audit cleanup, rollback, idempotency, stale versions, future Real and RLS passed.');
  } finally { await db.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
