const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const seed = require('./fixtures/fcPlanSeed.json');
const context = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../src/modules/params/fcPlanModule.js'), 'utf8'), context);
const { validateNode } = context.window.VECTON_FC_PLAN;
const nodes = seed.map(n => ({ ...n, id: n.seed_key, parent_id: n.parent_key, active: true }));
for (const node of nodes) validateNode(nodes, node);
assert.equal(nodes.length, 84);
assert.equal(nodes.filter(n => n.node_class === 'Analitica').length, 76);
assert.equal(new Set(nodes.map(n => n.id)).size, nodes.length);
const find = id => nodes.find(n => n.id === id);
assert.equal(find('linha-31').parent_id, 'linha-30');
assert.equal(find('linha-54').parent_id, 'linha-48');
assert.equal(find('linha-66').parent_id, 'linha-56');
assert.equal(find('linha-67').parent_id, 'saidas');
assert.equal(find('linha-71').parent_id, 'investimentos');
assert.equal(find('linha-92').parent_id, 'financeiro');
assert.throws(() => validateNode(nodes, { ...find('operacional'), parent_id: 'linha-30' }), /ciclo/);
assert.throws(() => validateNode(nodes, { ...find('linha-31'), parent_id: 'linha-32' }), /sintética/);
assert.throws(() => validateNode(nodes, { ...find('linha-30'), node_class: 'Analitica' }), /filhas/);
assert.throws(() => validateNode(nodes, { ...find('saidas'), active: false }), /Inative/);
assert.throws(() => validateNode(nodes, { ...find('linha-31'), source_name: '' }), /descrição/);
assert.throws(() => validateNode(nodes, { ...find('linha-31'), parent_id: null }), /conta pai/);
assert.throws(() => validateNode(nodes, { ...find('linha-31'), parent_id: 'another-org-parent' }), /existente/);
assert.throws(() => validateNode(nodes, { ...find('linha-31'), sort_order: -1 }), /ordem/);
assert.throws(() => validateNode(nodes, { ...find('linha-31'), id: 'new', source_name: '  comissao   revenda  ' }), /Já existe/);
const inactive = nodes.map(n => n.id === 'linha-30' ? { ...n, active: false } : n);
assert.throws(() => validateNode(inactive, find('linha-31')), /pai ativa/);
validateNode(nodes, { ...find('linha-31'), id: 'new', parent_id: 'financeiro' });
// The migration must seed the exact checked fixture, not a divergent copy.
const sql = fs.readFileSync(path.join(__dirname, '../supabase/219_fc_chart_of_accounts.sql'), 'utf8');
assert.deepEqual(JSON.parse(sql.split('$seed$')[1]), seed);
console.log('FC plan: seed, hierarchy, identity and validation checks passed.');
