/* Camada de apresentação isolada. Usa os metadados, a iconografia e a
   geometria geográfica do produto; nunca instancia serviços de produção. */
(() => {
  'use strict';
  const C = window.MOCKUP_CATALOG, D = window.MOCKUP_DATA;
  const $ = s => document.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const br = (n,d=1) => Number(n).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
  const money = n => `R$ ${br(n)} mi`;
  const badge = (text,tone='') => `<span class="badge ${tone}">${esc(text)}</span>`;
  const paths = {search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/>',chevron:'<path d="m9 5 7 7-7 7"/>',down:'<path d="m6 9 6 6 6-6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',plus:'<path d="M12 5v14M5 12h14"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',moon:'<path d="M20 14A8.5 8.5 0 0 1 10 4a8.5 8.5 0 1 0 10 10Z"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',back:'<path d="M19 12H5m5-5-5 5 5 5"/>',check:'<path d="m5 12 4 4L19 6"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18"/>',refresh:'<path d="M20 8a8 8 0 1 0 0 8M20 3v5h-5"/>',star:'<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1 6.2-5.5-2.9-5.5 2.9 1-6.2L3 9.6l6.2-.9Z"/>',link:'<path d="m10 13 5-5m-7 2-3 3a4 4 0 0 0 6 6l3-3m-4-8 3-3a4 4 0 0 1 6 6l-3 3"/>',edit:'<path d="m15 4 5 5M4 20l5-1L21 7l-5-5L4 14Z"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 4v3"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',sort:'<path d="m8 8 4-4 4 4M8 16l4 4 4-4"/>'};
  const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name] || `<use href="icons.svg#vp-icon-${name}"></use>`}</svg>`;
  const button = (text,action,ico='',style='') => `<button class="btn ${style}" type="button" data-action="${esc(action)}">${ico?icon(ico):''}${esc(text)}</button>`;
  const link = (text,id,ico='',style='') => `<button class="btn ${style}" type="button" data-go="${id}">${ico?icon(ico):''}${esc(text)}</button>`;
  const brand = () => `<div class="brand"><img src="../fav-icon.png" alt=""><div>vecton<small>PLANNING</small></div></div>`;
  let storedTheme='clear'; try {storedTheme=localStorage.getItem('vecton-mockup-theme')||'clear';} catch{}
  const state = {id:location.hash.slice(1)||'dashboard',theme:storedTheme,period:'Mês',month:'Set',management:'Marcher',region:'Norte',tab:'Todos',ui:'success',review:false,importStep:0,favorite:'Forecast 8+4',conversation:'Marina Costa',messages:[],localRows:{},formDraft:{},tableQuery:'',scope:'Todos',fcDelta:0};
  const screen = () => C.find(x=>x.id===state.id)||C[0];
  const factor = () => (state.period==='YTD'?8.1:state.period==='Ano'?12.2:1) * (state.month==='Ago'?.94:state.month==='Jul'?.89:1) * (state.management==='Marcher'?1:.36);
  const themeSwitch = () => `<div class="theme-switch" aria-label="Tema da interface">${['clear','dark'].map(t=>`<button type="button" data-theme-choice="${t}" aria-pressed="${state.theme===t}">${icon(t==='clear'?'sun':'moon')}${t==='clear'?'Clear':'Dark'}</button>`).join('')}</div>`;
  const nav = (id,label,ico) => `<button class="nav-link ${state.id===id?'active':''}" title="${esc(label)}" data-go="${id}" ${state.id===id?'aria-current="page"':''}>${icon(ico)}<span>${esc(label)}</span></button>`;
  function sidebar(){return `<aside class="sidebar" aria-label="Navegação principal">${brand()}<div class="workspace"><span class="square">M</span><div><b>Marcher Brasil</b><span class="meta">Workspace corporativo</span></div></div><nav><div class="nav-caption">Visão geral</div>${nav('dashboard','Cockpit Executivo','dashboard')}${nav('cockpit','Cockpit Gestão','gauge')}${nav('reports','Relatórios','reports')}<div class="nav-caption">Planejamento & gestão</div>${nav('planning','Cenários de forecast','planning')}${nav('strategic','A3 Estratégicos','target')}${nav('rps','RPS Gestão','activity')}${nav('rpsComercial','RPS Comercial','briefcase')}<div class="nav-caption">Workspace</div>${nav('messages','Messenger','chat')}${nav('parameters','Parâmetros','params')}${nav('commercialParameters','Cadastros comerciais','layers')}<div class="nav-caption">Avaliação do mockup</div>${nav('screenIndex','Todas as telas','layers')}${nav('designSystem','Design system','sliders')}</nav><div class="sidebar-footer">${themeSwitch()}<button class="profile-btn" data-go="profile"><div class="avatar">RG</div><div><b>Rafael Guimarães</b><small>Administrador</small></div>${icon('down')}</button><button class="nav-link" data-action="collapse">${icon('menu')}<span>Recolher navegação</span></button></div></aside>`;}
  // Entradas de agrupamento: mantêm todas as views reais acessíveis sem sobrecarregar a sidebar.
  C.push({id:'parameters',title:'Parâmetros',group:'Workspace',kind:'parameters',description:'Estruturas, cargas e administração da plataforma.'},{id:'commercialParameters',title:'Cadastros comerciais',group:'Workspace',kind:'commercialParameters',description:'Dados de referência e cargas da operação comercial.'});
  function topbar(){const s=screen();return `<header class="topbar"><div class="row"><button class="btn ghost icon-btn mobile-menu" data-action="menu" aria-label="Abrir navegação">${icon('menu')}</button><div class="breadcrumb"><span>${esc(s.group)}</span><span>/</span>${esc(s.title)}</div></div><div class="top-actions"><button class="global-search" data-action="search">${icon('search')}<span>Buscar no Vecton</span><kbd>Ctrl K</kbd></button><button class="btn ghost icon-btn" data-go="messages" aria-label="Abrir mensagens">${icon('chat')}</button><button class="btn ghost icon-btn notification-dot" data-action="notifications" aria-label="Abrir notificações">${icon('bell')}</button><button class="btn ghost icon-btn" data-go="profile" aria-label="Meu perfil"><span class="avatar">RG</span></button></div></header>`;}
  function toolbar(options={}){return `<div class="toolbar"><div class="row wrap"><div class="segmented" aria-label="Abrangência do período">${['Mês','YTD','Ano'].map(p=>`<button data-period="${p}" aria-pressed="${p===state.period}">${p}</button>`).join('')}</div><label>${icon('calendar')}<select aria-label="Competência" data-filter="month">${['Jul','Ago','Set'].map(m=>`<option ${state.month===m?'selected':''}>${m}</option>`).join('')}</select><span>2026</span></label>${options.noManagement?'':`<label>Gestão<select aria-label="Gestão" data-filter="management">${['Marcher',...D.areas].map(m=>`<option ${state.management===m?'selected':''}>${m}</option>`).join('')}</select></label>`}${options.source?`<label>Fonte<select aria-label="Fonte de comparação" data-filter="source"><option>${esc(state.favorite)}</option><option>Budget oficial</option></select></label>`:''}</div><span class="meta"><span class="context-dot"></span>${options.context||'Dados demonstrativos · 2026'}</span></div>`;}
  function kpis(items){return `<section class="kpis" aria-label="Indicadores principais">${items.map(([label,value,change,sub,tone='good',ico='trend-up'])=>`<div class="kpi"><div class="kpi-label">${esc(label)}${icon(ico)}</div><div class="kpi-value">${esc(value)}</div><div class="kpi-sub">${badge(change,tone)}<span>${esc(sub)}</span></div></div>`).join('')}</section>`;}
  function panel(title,sub,body,action=''){return `<section class="panel"><div class="panel-head"><div><h3>${esc(title)}</h3>${sub?`<p>${esc(sub)}</p>`:''}</div>${action}</div>${body}</section>`;}
  function chart(type='bars',values=[25,29,26,34,32,38,36,42,44],labels=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set']){
    const max=Math.max(...values)*1.2, xs=values.map((_,i)=>58+i*(560/(values.length-1))),y=v=>208-(v/max)*174;
    const grid=[0,1,2,3].map(i=>{const val=max*i/3;return `<line class="gridline" x1="42" y1="${y(val)}" x2="640" y2="${y(val)}"/><text x="30" y="${y(val)+3}" text-anchor="end">${br(val,0)}</text>`;}).join('');
    const labelsSvg=labels.map((l,i)=>`<text x="${xs[i]}" y="234" text-anchor="middle">${l}</text>`).join('');
    const line=values.map((v,i)=>`${i?'L':'M'}${xs[i]},${y(v)}`).join(' ');
    return `<svg class="chart" viewBox="0 0 664 250" role="img" aria-label="${type==='bars'?'Comparação mensal em barras':'Evolução mensal'}: ${values.map((v,i)=>`${labels[i]} ${br(v)}`).join('; ')}">${grid}${type==='bars'?values.map((v,i)=>`<g><title>${labels[i]} · Real: ${br(v)} · Budget: ${br(v*.94)}</title><rect class="bar2" x="${xs[i]-16}" y="${y(v*.94)}" width="13" height="${208-y(v*.94)}" rx="2"/><rect class="bar" x="${xs[i]+1}" y="${y(v)}" width="13" height="${208-y(v)}" rx="2"/></g>`).join(''):`<path class="area" d="${line} L${xs.at(-1)},208 L${xs[0]},208Z"/><path class="line2" d="${values.map((v,i)=>`${i?'L':'M'}${xs[i]},${y(v*.85)}`).join(' ')}"/><path class="line" d="${line}"/>${values.map((v,i)=>`<circle cx="${xs[i]}" cy="${y(v)}" r="3.5" fill="var(--chart)"><title>${labels[i]}: ${br(v)}</title></circle>`).join('')}`}${labelsSvg}</svg>`;
  }
  const legend = (a='Realizado',b='Budget')=>`<div class="legend"><span><i class="secondary"></i>${esc(b)}</span><span><i></i>${esc(a)}</span></div>`;
  function ranking(rows,unit='mi'){const max=Math.max(...rows.map(r=>r[1]));return `<div class="panel-body">${rows.map(([name,val],i)=>`<div class="rank-row"><span class="rank-index">${String(i+1).padStart(2,'0')}</span><div>${esc(name)}<div class="rank-track"><i style="width:${val/max*100}%"></i></div></div><strong>${unit==='mi'?money(val):br(val,0)+' '+unit}</strong></div>`).join('')}</div>`;}
  function table(headers,rows,opts={}){return `<div class="table-scroll"><table><thead><tr>${headers.map((h,i)=>`<th class="${i&&(opts.numeric??true)?'num':''}" scope="col"><button data-sort="${i}" aria-label="Ordenar por ${esc(h)}">${esc(h)}${icon('sort')}</button></th>`).join('')}</tr></thead><tbody>${rows.map((row,j)=>`<tr ${opts.total&&j===rows.length-1?'class="total"':''}>${row.map((cell,i)=>`<td class="${i&&(opts.numeric??true)?'num':''}">${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${opts.footer===false?'':`<div class="table-foot"><span>${rows.length} registros · ${opts.unit||'Dados demonstrativos'}</span><span>${opts.hint||'Selecione uma linha para detalhar'}</span></div>`}`;}
  const drill = (name,type='financial')=>`<button class="table-link" data-drill="${esc(name)}" data-drill-type="${type}">${icon('chevron')}${esc(name)}</button>`;
  const tableSearch = ()=>`<input class="table-search" type="search" aria-label="Buscar nesta tabela" placeholder="Buscar nesta tabela…" data-table-search>`;
  function financialRows(data){return data.map(([label,real,budget])=>[drill(label),money(real*factor()),money(budget*factor()),`<span class="${real>=budget?'positive':'negative'}">${br((real-budget)/Math.abs(budget)*100)}%</span>`]);}
  const tabs = (names,active=state.tab,attr='tab')=>`<div class="tabs" role="group" aria-label="Seções">${names.map(n=>`<button class="${active===n?'active':''}" data-${attr}="${esc(n)}">${esc(n)}</button>`).join('')}</div>`;
  const insight = (title,text)=>`<div class="insight">${icon('activity')}<div><strong>${esc(title)}</strong> ${esc(text)}</div></div>`;
  function executive(){const f=factor();return toolbar({source:true})+kpis([
    ['Receita líquida',money(42*f),'+4,3%','vs Budget'],['EBITDA',money(8.4*f),'20,0%','margem EBITDA'],['Despesas operacionais',money(9.6*f),'−5,0%','vs Budget'],['Headcount','256','−6 pessoas','vs Budget','', 'users']
  ])+`<div class="grid2">${panel('Receita líquida','Evolução mensal · R$ milhões',`<div class="panel-body">${chart('bars',[28,31,29,35,33,39,37,39.48,42])}</div>`,legend())}${panel('Composição das despesas','Participação no OPEX do período',ranking(D.opex.map(([n,v])=>[n,v*f])),link('Detalhar','opexReal','arrow','ghost'))}</div>`+insight('Resultado acima do planejado.',`EBITDA de ${money(8.4*f)}, com despesas operacionais 5,0% abaixo do Budget. Explore as contas para entender a composição.`)+panel('Síntese do resultado',`${state.month}/2026 · ${state.period} · ${state.management}`,table(['Indicador','Realizado','Budget','Δ %'],financialRows([D.dre[2],D.dre[4],D.dre[5],D.dre[6],D.dre[11]])),link('Abrir DRE','dreGerReal','arrow','ghost'));}
  function cockpit(){const f=factor();return toolbar({source:true})+kpis([
    ['OPEX do período',money(9.6*f),'95,0%','aderência ao Budget'],['Headcount médio',br(state.management==='Marcher'?256:92,0),'262','Budget','', 'users'],['OPEX / pessoa',`R$ ${br(37500*(state.period==='Mês'?1:1.02),0)}`,'−2,7%','vs Budget'],['OPEX / receita','22,9%','−2,2 p.p.','vs Budget']
  ])+`<div class="grid2">${panel('Evolução do OPEX','R$ milhões · realizado e comparativo',`<div class="panel-body">${chart('line',[8.2,8.5,8.1,9.0,8.8,9.1,9.2,9.4,9.6])}</div>`,legend())}${panel('Raio-X por área','Pessoas e distribuição da estrutura',ranking(D.people.map(([n,v])=>[n,v]),'pessoas'),link('Headcount','headcountReal','arrow','ghost'))}</div>`+panel('OPEX por grupo de despesa','Despesas menores são favoráveis',table(['Grupo de despesa','Realizado','Budget','Aderência'],D.opex.map(([n,r,b])=>[drill(n),money(r*f),money(b*f),badge(br(r/b*100)+'%','good')])),tableSearch());}
  function catalog(kind='reports'){
    let items=kind==='reports'?C.filter(s=>s.section):C.filter(s=>kind==='parameters'?s.group==='Parâmetros':s.group==='Cadastros comerciais');
    const sections=kind==='reports'?['Comercial','Fluxo de Caixa','DRE','OPEX','Headcount','Personalizados']:kind==='parameters'?['Estruturas','Cargas','Administração']:['Cadastros','Cargas comerciais'];
    const groupOf=s=>s.section||(kind==='parameters'?(s.kind==='tree'||s.id==='managements'?'Estruturas':s.kind==='import'?'Cargas':'Administração'):(s.kind==='import'?'Cargas comerciais':'Cadastros'));
    return `<div class="toolbar"><input type="search" placeholder="Buscar ${kind==='reports'?'relatórios':'parâmetros'}…" aria-label="Buscar no catálogo" data-catalog-search style="width:320px"><span class="meta">${items.length} ${kind==='reports'?'relatórios':'telas disponíveis'}</span></div>${sections.map(section=>`<section class="catalog-section"><div class="section-title"><h2>${section}</h2><span class="meta">${items.filter(s=>groupOf(s)===section).length} itens</span></div><div class="catalog-grid">${items.filter(s=>groupOf(s)===section).map(s=>`<button class="catalog-card" data-go="${s.id}">${icon(s.kind==='import'?'upload':s.kind==='tree'?'branch':s.kind==='headcount'?'users':s.kind==='map'||s.kind==='parts'?'target':s.kind==='cashflow'?'dollar':'reports')}<b>${esc(s.title)}</b><p>${esc(s.description)}</p></button>`).join('')}</div></section>`).join('')}`;
  }
  function sales(matrix=false){const rows=D.sales.filter(r=>state.scope==='Todos'||r[0]===state.scope),f=factor(),sum=rows.reduce((a,r)=>a+r[1],0),target=rows.reduce((a,r)=>a+r[2],0),quantity=rows.reduce((a,r)=>a+r[3],0);return toolbar({noManagement:true})+`<div class="toolbar"><div class="row wrap"><label>Coordenação<select data-filter="scope" aria-label="Coordenação">${['Todos',...D.sales.map(r=>r[0])].map(v=>`<option ${state.scope===v?'selected':''}>${v}</option>`).join('')}</select></label><span class="badge blue">Máquinas</span><span class="meta">Valor e volume no mesmo recorte</span></div>${link('Mapa geográfico','comercialMapaGeografico','target','ghost')}</div>`+kpis([
    ['Faturamento',money(sum*f),br(sum/target*100)+'%','da meta'],['Volume',br(Math.round(quantity*f),0)+' un.','Máquinas','vendidas',''],['Ticket médio','R$ 300 mil','Faturamento','/ volume',''],['Meta de faturamento',money(target*f),money((sum-target)*f),'desvio absoluto',sum>=target?'good':'warn']
  ])+(!matrix?`<div class="grid2">${panel('Faturamento por mês','R$ milhões · máquinas',`<div class="panel-body">${chart('bars',[24,28,27,32,31,36,37,39.48,42].map(v=>v*sum/42))}</div>`,legend('Realizado','Meta'))}${panel('Performance por coordenação','Faturamento no período',ranking(rows.map(([n,v])=>[n,v*f])))}</div>`:'')+panel(matrix?'Matriz territorial':'Resultados por coordenação','Brasil · máquinas · faturamento e volume',table(['Coordenação','Realizado','Meta','Atingimento','Volume'],rows.map(([n,r,b,q])=>[drill(n,'sales'),money(r*f),money(b*f),badge(br(r/b*100)+'%',r>=b?'good':'warn'),br(Math.round(q*f),0)]).concat([[`<strong>Total</strong>`,money(sum*f),money(target*f),br(sum/target*100)+'%',br(Math.round(quantity*f),0)]]),{total:true}),tableSearch());}
  function financial(s){const planned=s.id.includes('Budget');let data=s.kind==='opex'?D.opex:s.kind==='customReport'?D.dre.filter((_,i)=>[2,5,6].includes(i)):D.dre;
    let headers=['Descrição','Jul','Ago',`${state.month} · ${planned?'Planejado':'Real'}`,'Total do recorte'];
    if(s.kind==='headcount'){data=D.people;headers=['Gestão / centro de custo','Jul','Ago',`${state.month} · ${planned?'Planejado':'Real'}`,'Média do recorte'];}
    const selectedIndex=planned?2:1;
    const fmt=s.kind==='headcount'?n=>br(n,0):n=>money(n);
    return toolbar({source:planned})+tabs(s.kind==='dre'?['Societário','Gerencial','DFs']:['Por gestão','Por centro de custo'],s.kind==='dre'?(s.id.includes('Soc')?'Societário':s.id.includes('Dfs')?'DFs':'Gerencial'):(state.tab==='Todos'?'Por gestão':state.tab),'report-tab')+panel(s.title,s.kind==='headcount'?'Pessoas · média mensal no acumulado':'Valores em R$ milhões · percentual total ponderado pela receita líquida',table(headers,data.map((r,i)=>[drill(r[0],s.kind==='headcount'?'people':'financial'),fmt(r[selectedIndex]*.89),fmt(r[selectedIndex]*.94),fmt(r[selectedIndex]),fmt(r[selectedIndex]*(s.kind==='headcount'?1:factor()))])),tableSearch())+(s.kind==='dre'?`<div class="insight" style="margin-top:20px">${icon('activity')}<div><strong>Margem EBITDA: ${planned?'17,1%':'20,0%'}</strong> · EBITDA / receita líquida do mesmo período. O total usa a razão entre os valores acumulados.</div></div>`:'');}
  function geographic(parts=false){const hot=['RS','MT','PR','GO','SP','SC'];const geo=window.VECTON_BR_GEO;
    const map=`<svg class="map" viewBox="0 0 440 410" role="group" aria-label="Mapa de vendas por estado">${geo.states.map(s=>{const path=s.rings.map(r=>r.map(([x,y],i)=>`${i?'L':'M'}${((x+74)*10+20).toFixed(1)},${((5.5-y)*10+8).toFixed(1)}`).join(' ')+'Z').join(' ');return `<path class="${hot.includes(s.uf)?'hot':''}" d="${path}" tabindex="0" role="button" data-drill="${s.nome}" data-drill-type="sales" aria-label="Detalhar ${s.nome}"><title>${s.nome} · abrir detalhamento</title></path>`;}).join('')}</svg>`;
    return toolbar({noManagement:true})+kpis(parts?[
      ['Faturamento de peças',money(3.6),'102,9%','da meta'],['Clientes atendidos','84','120','clientes na carteira',''],['Cobertura','70,0%','84 / 120','clientes',''],['Sem compra há 90 dias','18','Acompanhar','reativação','warn']
    ]:[['Faturamento · Brasil',money(36),'120 un.','máquinas',''],['Exterior / EX',money(6),'20 un.','máquinas',''],['Faturamento total',money(42),'140 un.','Brasil + Exterior',''],['Ticket médio','R$ 300 mil','R$ 42 mi / 140','por máquina','']])+`<div class="grid2 equal">${panel(parts?'Cobertura geográfica da carteira':'Distribuição do faturamento','Selecione uma UF para aprofundar a análise',`<div class="panel-body map-wrap">${map}</div>`)}${panel('Ranking por UF',parts?'Peças · faturamento':'Máquinas · faturamento',ranking((parts?[['RS',1.2],['MT',.8],['PR',.6],['GO',.4],['SP',.3],['SC',.3]]:[['RS',10.2],['MT',9],['PR',6.6],['GO',4.8],['SP',3],['SC',2.4]])))}</div>`+panel(parts?'Carteira e oportunidade de reativação':'Vendas por UF e cliente','Mesmo recorte do mapa e dos indicadores',table(parts?['Cliente','UF','Última compra','Faturamento','Situação']:['UF','Cliente','Volume','Faturamento'],parts?D.registries.comClientes.map((r,i)=>[drill(r[1],'sales'),r[2].split('/')[1],'12/09/2026',money(.12*(i+1)),badge(i===3?'Sem compra há 90 dias':'Ativo',i===3?'warn':'good')]):[['RS','Agro Horizonte',34,10.2],['MT','Fazenda Primavera',30,9],['PR','Cooperativa Campo Novo',22,6.6],['GO','Estância Boa Vista',16,4.8],['SP','Agro Central',10,3],['SC','Agro Sul',8,2.4],['EX','Cliente internacional',20,6]].map(([uf,n,q,v])=>[uf,drill(n,'sales'),q,money(v)])),tableSearch());}
  const cashRows=[['Saldo inicial','opening'],['Recebimentos operacionais','receipt'],['Pagamentos operacionais','payment'],['Caixa operacional','operating'],['Investimentos','investment'],['Financiamentos','financing'],['Geração líquida','net'],['Saldo final','closing']];
  function cashflow(){const model=window.MOCKUP_CASH,summary=model.summarize(state.period,state.month);const trend=state.period==='Mês'?model.calculate().slice(0,model.months.indexOf(state.month)+1):summary.rows;return toolbar({noManagement:true,context:'Base demonstrativa · posições de saldo'})+kpis([
    ['Saldo final',money(summary.closing),'Posição','no fim do período',''],['Geração líquida',money(summary.net),'Entradas − saídas','no período',summary.net>=0?'good':'warn'],['Caixa operacional',money(summary.operating),'Operação','no período',''],['Menor saldo',money(summary.min),'Posição mínima','no recorte','']
  ])+`<div class="grid2">${panel('Evolução do saldo de caixa','R$ milhões · posições mensais, não acumuladas',`<div class="panel-body cash-chart">${chart('line',trend.map(r=>r.closing),trend.map(r=>r.month))}</div>`,`<span class="meta">Set–Dez: Fcst</span>`)}${panel('Principais saídas operacionais','R$ milhões · ordem decrescente',ranking([['Fornecedores',24],['Pessoal',4.8],['Tributos',2.4],['Demais saídas',1.2]].map(([n,v])=>[n,v/32.4*Math.abs(summary.payment)])))}</div>`+panel('Demonstrativo de caixa',`${state.month}/2026 · ${state.period} · base demonstrativa`,table(['Descrição','R$ milhões'],cashRows.map(([n,key])=>[drill(n),br(summary[key])]),{total:true}),link('FC detalhado','fcDetail','arrow','ghost'));}
  function cashDetail(){const model=window.MOCKUP_CASH,months=model.months,all=model.calculate(),summary=model.summarize('Ano',state.month);return toolbar({noManagement:true})+insight('Simulação de cenário.', 'Meses Real ficam protegidos. Editar uma entrada futura recalcula o caixa dos meses seguintes nesta prévia.')+panel('Fluxo de caixa anual','Valores em R$ milhões · quantidades em unidades · Set a Dez: Fcst',table(['Conta',...months.map((m,i)=>`${m} · ${i<8?'Real':'Fcst'}`),'2026'],[...cashRows,['Máquinas vendidas (un.)','quantity']].map(([n,key])=>[drill(n),...all.map((row,i)=>i>=8&&['receipt','payment','investment','financing','quantity'].includes(key)?`<input class="edit-cell" aria-label="${esc(n)} ${months[i]}" data-fc-input="${key}" data-fc-month="${i}" value="${br(row[key],key==='quantity'?0:2)}" inputmode="decimal">`:br(row[key],key==='quantity'?0:1)),br(summary[key],key==='quantity'?0:1)]),{unit:'R$ milhões / unidades',hint:'Saldo anual: posição. Fluxos anuais: soma.'}),link('Cenários salvos','fcScenarios','layers','ghost'))+`<div class="form-actions">${link('Voltar ao dashboard','cashFlow','back')}${button('Desfazer','fcUndo','refresh')}${button('Salvar novo cenário','saveFc','plus','primary')}</div>`;}
  function planning(fc=false){const rows=fc?[['Carga oficial','Compartilhado','Base anual','Referência'],['Caixa · conservador','Pessoal','Set–Dez/2026','Simulação'],['Caixa · expansão','Compartilhado','Set–Dez/2026','Simulação']]:[['Budget oficial 2026','Budget','Jan–Dez/2026','Base oficial'],['Forecast 8+4','Forecast','Real Jan–Ago + Fcst Set–Dez','Favorito'],['Cenário conservador','Forecast','Real Jan–Ago + Fcst Set–Dez','Rascunho'],['Cenário expansão','Forecast','Real Jan–Ago + Fcst Set–Dez','Rascunho']];return `<div class="toolbar"><div class="row"><label>Ano<select aria-label="Ano"><option>2026</option></select></label><span class="meta">${rows.length} cenários disponíveis</span></div>${fc?'':link('Comparar cenários','scenarioCompare','layers')}</div>`+panel(fc?'Biblioteca de cenários de caixa':'Cenários de resultado',fc?'Visibilidade por autor e organização':'A estrela define a fonte favorita nos relatórios e no Cockpit Gestão',table(['Nome','Tipo / visibilidade','Composição','Status','Ações'],rows.map(([name,type,period,status])=>[`<button class="table-link" data-go="${fc?'fcDetail':'scenarioEdit'}">${icon('planning')}${esc(name)}</button>`,esc(type),esc(period),badge(status,status==='Favorito'?'blue':''),fc?button('Abrir','openFc','arrow','ghost'):`<button class="btn ghost icon-btn" data-favorite="${esc(name)}" aria-label="Favoritar ${esc(name)}" style="color:${state.favorite===name?'var(--accent)':'var(--text-muted)'}">${icon('star')}</button>`]),{numeric:false}),tableSearch());}
  function cashScenarios(){return insight('Cenários desta avaliação.', 'Salve uma simulação no FC detalhado para compará-la com a carga oficial. As cópias ficam disponíveis até recarregar a página.')+panel('Biblioteca de cenários','Visibilidade compartilhada para o perfil Administrador',table(['Cenário','Visibilidade','Período','Ação'],[['Carga oficial · exemplo','Compartilhado','2026',button('Abrir base','cashOpen:-1','arrow','ghost')],...window.MOCKUP_CASH.scenarios.map((s,i)=>[esc(s.name),'Compartilhado','2026',button('Abrir cenário',`cashOpen:${i}`,'arrow','ghost')])],{numeric:false,hint:'Persistência local à sessão do mockup'}));}
  function scenario(compare=false){return toolbar({source:true})+(compare?kpis([['Budget · receita',money(504),'Base','2026',''],['Forecast · receita',money(518.4),'+2,9%','vs Budget'],['Conservador · receita',money(480),'−4,8%','vs Budget','warn'],['Expansão · receita',money(552),'+9,5%','vs Budget']]):insight('Forecast 8+4.', 'Janeiro a agosto preservam o realizado. Setembro a dezembro recebem os valores planejados.'))+panel(compare?'Comparativo anual':'Premissas do cenário',compare?'R$ milhões · mesma base temporal':'R$ milhões · ajuste os meses futuros',table(compare?['Indicador','Budget oficial','Forecast 8+4','Conservador','Expansão']:['Indicador','Real Jan–Ago','Set','Out','Nov','Dez'],D.dre.filter((_,i)=>[2,5,6,11].includes(i)).map(([n,v])=>compare?[esc(n),br(v*12),br(v*12.3),br(v*11.4),br(v*13.1)]:[esc(n),br(v*8),...[1,1.1,1.05,1.2].map((f,i)=>`<input class="edit-cell" aria-label="${esc(n)} ${['Set','Out','Nov','Dez'][i]}" value="${br(v*f)}">`)])),compare?'':button('Salvar alterações','saveScenario','check','primary'));}
  function registry(s){const rows=state.localRows[s.id]||D.registries[s.id]||[];return `<div class="toolbar"><input type="search" aria-label="Buscar registros" data-table-search placeholder="Buscar por código ou descrição…" style="width:320px"><span class="meta">${rows.length} registros · cadastro de referência</span></div>`+panel(s.title,'Selecione um registro para editar',table([...s.columns,''],rows.map((r,i)=>[...r.map((c,j)=>j===1?`<button class="table-link" data-edit-row="${i}">${esc(c)}</button>`:c==='Ativo'?badge(c,'good'):esc(c)),`<button class="btn ghost icon-btn" data-edit-row="${i}" aria-label="Editar ${esc(r[1])}">${icon('edit')}</button>`]),{numeric:false,hint:'Alterações apenas nesta sessão do mockup'}));}
  function tree(s){const fc=s.id==='fcPlan',cc=s.id==='ccPlan',branch=s.id==='branchPlan';const names=branch?['Marcher Brasil','Matriz Gravataí','Filial Mato Grosso']:cc?['Centros de custos','Industrial','Produção','Manutenção','Comercial','Vendas nacionais','Exportação']:fc?['Fluxo de Caixa','Atividades operacionais','Recebimento de clientes','Pagamento a fornecedores','Atividades de investimento','Atividades de financiamento']:['Demonstração do resultado','Receita operacional','Receita de máquinas','Receita de peças','Custos dos produtos','Despesas operacionais','Pessoal e encargos'];const selected=state.treeName||names[2];return `<div class="tree-layout">${panel('Estrutura','Selecione um item para editar',`<div class="panel-body"><input type="search" placeholder="Buscar na estrutura…" aria-label="Buscar na estrutura" data-tree-search style="width:100%;margin-bottom:16px">${names.map((n,i)=>`<button class="tree-row ${i>0?'sub':''} ${i===2||i===3?'deep':''} ${n===selected?'active':''}" data-tree="${esc(n)}" style="width:100%;border:0;background:${n===selected?'var(--selected)':'transparent'}">${icon(i<2?'down':'accounts')}<code>${i===0?'':`1.${i}`}</code>${esc(n)}</button>`).join('')}</div>`)}${panel('Detalhes do item','Cadastro e classificação',`<form class="panel-body" data-local-form="tree"><div class="form-grid"><label class="field">Código<input value="1.2" required></label><label class="field">Classe<select><option>Analítica</option><option>Sintética</option></select></label><label class="field full">Descrição<input name="description" value="${esc(selected)}" required></label><label class="field full">${cc?'Gestão':branch?'UF':fc?'Natureza':'Conta contábil vinculada'}<input value="${cc?'Industrial':branch?'RS':fc?'Entrada':'31101001'}" required></label><label class="field full">Grupo superior<select><option>${names[1]}</option><option>${names[0]}</option></select></label></div><div class="form-actions"><button class="btn primary" type="submit">Salvar alterações</button></div></form>`)}</div>`;}
  function imports(s){return `<div class="steps">${['Selecionar arquivo','Validar dados','Aplicar carga'].map((n,i)=>`<div class="step ${state.importStep===i?'active':''}"><b>${i+1}</b>${n}</div>`).join('')}</div><div class="grid2 equal">${panel('Nova carga','Lote independente com histórico de aplicação',`<div class="panel-body stack"><div class="form-grid"><label class="field">Competência<select><option>Setembro / 2026</option><option>Agosto / 2026</option></select></label><label class="field">${s.id==='headcountLoad'?'Fonte':'Empresa'}<select><option>${s.id==='headcountLoad'?'Realizado':'Marcher Brasil'}</option><option>${s.id==='headcountLoad'?'Planejado':'Matriz Gravataí'}</option></select></label></div><div class="dropzone">${icon('upload')}<h3>Selecione o arquivo da carga</h3><p>${s.id==='fcLoad'?'Arquivo anual com as 12 competências':'Planilha ou arquivo de dados da competência'}</p><label class="btn">${icon('file-plus')}Escolher arquivo<input type="file" data-upload style="max-width:180px;font-size:11px" aria-label="Arquivo da carga" accept=".xlsx,.xls,.csv,.txt"></label><span class="meta">Prévia visual · nenhum arquivo é enviado</span></div>${link('Abrir exemplo de validação','importReview','arrow','primary')}</div>`)}${panel('Orientações de importação','Rastreabilidade em todas as etapas',`<div class="panel-body stack"><div><h3>01 · Prepare os dados</h3><p class="muted small">Use as colunas e classificações previstas para esta carga.</p></div><div><h3>02 · Confira a validação</h3><p class="muted small">Corrija inconsistências de conta, centro de custo, competência ou vínculo.</p></div><div><h3>03 · Aplique o lote</h3><p class="muted small">A aplicação no produto mantém os registros de auditoria. Aqui, a operação é apenas simulada.</p></div>${s.id==='actualsLoad'?link('Carga de Fluxo de Caixa','fcLoad','arrow'):s.id==='budgetLoad'?link('Vendas planejadas','comercialPlanejado','arrow'):''}</div>`)}</div>`+panel('Histórico de cargas','Aplicações da competência selecionada',table(['Arquivo','Competência','Linhas','Status','Aplicação'],[['base_setembro_2026.xlsx','Set/2026','1.248',badge('Aplicado','good'),'22/09/2026 · 16:42'],['base_agosto_2026.xlsx','Ago/2026','1.196',badge('Aplicado','good'),'05/09/2026 · 09:15']],{numeric:false}),tableSearch());}
  function importReview(){return insight('Validação concluída com pendências.', '1.246 linhas válidas e 2 inconsistências no lote demonstrativo. A aplicação fica desabilitada até a correção.')+kpis([['Linhas lidas','1.248','Arquivo','demonstrativo',''],['Linhas válidas','1.246','99,8%','do lote'],['Inconsistências','2','Revisar','antes de aplicar','warn'],['Status','Em revisão','Pendente','correção','warn']])+panel('Log de validação','Inconsistências que impedem a aplicação',table(['Linha','Campo','Valor','Mensagem'],[['248','Conta','99999999','Conta não encontrada no plano'],['912','Centro de custo','CC-000','Centro de custo sem vínculo de gestão']],{numeric:false,hint:'Corrija o arquivo e valide novamente'}))+`<div class="form-actions">${button('Simular arquivo corrigido','validate','refresh')}<button class="btn primary" data-action="applyImport" disabled>Aplicar lote demonstrativo</button></div>`;}
  function strategic(){return toolbar({noManagement:true,context:'Ciclo estratégico 2026'})+panel('Norte Verdadeiro','Metas anuais que orientam a organização',kpis([['Receita líquida','R$ 504 mi','Meta anual','2026',''],['Margem EBITDA','20,0%','Meta anual','2026',''],['Entregas no prazo','95,0%','Meta anual','2026',''],['Satisfação do cliente','85 pontos','Meta anual','NPS','']]),button('Editar metas','northGoals','edit','ghost'))+`<div style="height:24px"></div>`+panel('Áreas estratégicas','Indicadores, desdobramentos e planos de ação',`<div class="a3-list">${D.areas.map((n,i)=>`<button class="a3-row" data-go="a3Detail"><span class="square">${String(i+1).padStart(2,'0')}</span><div><b>A3 ${n}</b><small>${4+i%3} indicadores · ${i%2+1} desdobramentos</small></div>${badge(`${2+i%3}/${4+i%3} na meta`,i%3===0?'warn':'good')}${icon('chevron')}</button>`).join('')}</div>`,link('Arquivados','a3Archived','layers','ghost'));}
  function a3(entry=false){return toolbar({noManagement:true,context:'Industrial · responsável: Marina Costa'})+`<div class="tabs">${[['a3Detail','Visão do A3'],['a3Entry','Lançamento mensal'],['a3Actions','Plano de ação']].map(([id,n])=>`<button class="${id===state.id?'active':''}" data-go="${id}">${n}</button>`).join('')}</div>`+(entry?insight('Competência aberta.', 'Preencha o realizado. Ausência de informação permanece sem dado; zero representa um valor informado.'):kpis([['Indicadores na meta','2 de 4','50,0%','com informação','warn'],['Plano de ação','6 ações','2 em atenção','por prazo','warn'],['Eficiência operacional','88,2%','+3,2 p.p.','vs meta'],['Entregas no prazo','92,4%','−2,6 p.p.','vs meta','warn']]))+panel(entry?'Entrada de indicadores':'Metas e realizado',`${state.month}/2026 · Industrial`,table(['Indicador','Unidade','Meta','Realizado','Direção','Situação / evidência'],D.kpis.map(([n,u,target,actual,direction],i)=>[drill(n,'kpi'),u,br(target),entry?`<input class="edit-cell" aria-label="Realizado de ${esc(n)}" value="${br(actual)}">`:br(actual),direction,entry?button('Anexar','attachment','link','ghost'):badge(i%2===0?'Na meta':'Fora da meta',i%2===0?'good':'warn')]),{numeric:false}),entry?button('Salvar lançamentos','saveEntries','check','primary'):button('Fechar competência','closePeriod','lock'))+(!entry?`<div class="grid2 equal" style="margin-top:24px">${panel('Eficiência operacional','% · meta 85,0',`<div class="panel-body">${chart('line',[79,81,80,83,82,85,86,87,88.2])}</div>`)}${panel('Análise crítica','Causa, contramedida e acompanhamento',`<div class="panel-body stack"><div>${badge('Em atenção','warn')}<h3 style="margin:12px 0 8px">Entregas abaixo da meta</h3><p class="small muted">Concentração de pedidos no fim do mês e restrições de componentes impactaram o prazo de entrega.</p></div><div><h3>Próximo passo</h3><p class="small muted">Revisar sequenciamento e acompanhar itens críticos com Supply Chain.</p></div>${link('Abrir plano de ação','a3Actions','arrow')}</div>`)}</div>`:'');}
  function actions(){return `<div class="toolbar"><span class="meta">A3 Industrial · Setembro / 2026</span>${link('Voltar ao A3','a3Detail','back','ghost')}</div><div class="board">${['A fazer','Em andamento','Concluído'].map((n,i)=>`<section class="board-col"><div class="row between"><h3>${n}</h3>${badge('2')}</div>${['Revisar sequência de produção','Acompanhar fornecedores críticos'].map((task,j)=>`<article class="task">${badge(j?'Entregas no prazo':'Eficiência operacional',i===2?'good':'blue')}<p>${task}${i===2?' · ciclo anterior':''}</p><div class="row between"><span class="avatar">${j?'AF':'MC'}</span><span class="meta">${i===2?'Concluído em 18/09':'Prazo: 30/09/2026'}</span></div><div class="form-actions">${button('Detalhar','editAction','arrow','ghost')}</div></article>`).join('')}</section>`).join('')}</div>`;}
  function rps(present=false){return `<div class="toolbar"><div class="row wrap"><label>${icon('calendar')}<select aria-label="Mês da RPS"><option>Setembro / 2026</option></select></label><label>Área<select data-filter="management" aria-label="Área da RPS">${['Marcher',...D.areas].map(a=>`<option ${state.management===a?'selected':''}>${a}</option>`).join('')}</select></label></div>${link('Histórico e backups','rpsHistory','refresh','ghost')}</div>`+(present?insight('Modo apresentação.', 'Indicadores da semana organizados para a reunião de acompanhamento.'):'')+panel(state.management==='Marcher'?'Industrial · indicadores semanais':`${state.management} · indicadores semanais`,'Semana 4 · 21 a 27 de setembro',table(['Indicador','S1','S2','S3','S4','Mês','Meta','Desvio'],[['Eficiência operacional',84,86,88,88.2,86.55,85,1.55],['Entregas no prazo',90,93,94,92.4,92.35,95,-2.65],['Índice de retrabalho',2.2,2.0,1.8,1.8,1.95,2,-.05],['Horas de parada',12,10,11,13,46,40,6]].map(([n,...values])=>[drill(n,'kpi'),...values.map((v,i)=>i===3&&!present?`<input class="edit-cell" aria-label="${esc(n)} semana 4" value="${br(v)}">`:br(v))])),present?'':button('Salvar semana','saveRps','check','primary'))+`<div class="grid2 equal" style="margin-top:24px">${panel('Comentários da semana','Contexto dos desvios e acompanhamento',`<div class="panel-body"><label class="field">Análise da área<textarea ${present?'readonly':''}>Evolução da eficiência após revisão do sequenciamento. Entregas permanecem em acompanhamento com a equipe de logística.</textarea></label>${button('Salvar comentário','saveComment','check','ghost')}</div>`)}${panel('Evidências e anexos','Arquivos de suporte aos indicadores',`<div class="panel-body"><button class="attachment" data-action="attachment">${icon('reports')}Relatório semanal · exemplo</button>${button('Adicionar evidência','attachment','plus','ghost')}</div>`)}</div>`;}
  function rpsCommercial(present=false){return `<div class="toolbar"><label>${icon('calendar')}Semana<select aria-label="Semana comercial"><option>21–27 set. 2026</option><option>14–20 set. 2026</option></select></label><span class="meta">Coordenação: ${esc(state.region)} · reunião semanal</span></div>`+tabs(D.commercialAreas,state.region,'region')+panel(`Comercial ${state.region}`,'Ata semanal · responsável: equipe comercial',`${['Semana anterior','Planejamento da semana atual','Comentários diversos'].map((n,i)=>`<div class="rps-block"><label for="rps-text-${i}">${String(i+1).padStart(2,'0')} · ${n}</label><textarea id="rps-text-${i}" ${present?'readonly':''}>${esc(state.formDraft[`rps${state.region}${i}`]||[`${state.region}: acompanhamento das propostas em negociação, visitas a clientes e alinhamento das entregas da semana.`,`Priorizar propostas com previsão de fechamento, realizar visitas da carteira e revisar o planejamento com a coordenação.`,`Consolidar os retornos dos clientes e compartilhar pendências com as áreas de apoio.`][i])}</textarea><div class="row between wrap"><button class="attachment" data-action="attachment">${icon('link')}Anexos e comentários</button>${present?'':button('Salvar bloco',`saveRpsBlock:${i}`,'check','ghost')}</div></div>`).join('')}`);}
  function history(archived=false){return panel(archived?'Itens arquivados':'Histórico de versões',archived?'Restaure um item para retomar seu acompanhamento':'RPS Gestão · snapshots e backups recuperáveis',table(archived?['Item','Área','Arquivado em','Ação']:['Versão','Competência','Origem','Integridade','Ação'],archived?[['A3 · Melhoria de processos','Industrial','01/09/2026',button('Restaurar','restore','refresh','ghost')],['Indicador · Tempo de setup','Industrial','12/09/2026',button('Restaurar','restore','refresh','ghost')]]:[['22/09/2026 · 18:30','Set/2026','Backup agendado',badge('Verificado','good'),button('Consultar versão','snapshot','reports','ghost')],['21/09/2026 · 09:10','Set/2026','Salvamento manual',badge('Verificado','good'),button('Consultar versão','snapshot','reports','ghost')]],{numeric:false}));}
  function builder(commercial=false){const names=commercial?['Desempenho de um vendedor','Comparativo do time','Performance por vendedor e cultura','Campanha (avançado)']:['Configuração','Linhas e fórmulas','Colunas e fontes','Pré-visualização'];return commercial?`<div class="catalog-grid">${names.map((n,i)=>`<button class="catalog-card" data-action="template:${i}">${icon(i===3?'target':'reports')}<b>${n}</b><p>${['Evolução mensal de volume, faturamento e margem.','Compare o resultado de cada integrante da equipe.','Faturamento ou margem por cultura e vendedor.','Defina elegibilidade, metas, ranking e premiação.'][i]}</p></button>`).join('')}</div><div style="height:24px"></div>`+builderForm(true):tabs(names,state.tab==='Todos'?'Configuração':state.tab)+builderForm(false);}
  function builderForm(commercial){return `<div class="grid2 equal">${panel('Definição do relatório','Configuração demonstrativa',`<form class="panel-body" data-local-form="builder"><div class="form-grid"><label class="field full">Nome do relatório<input value="${commercial?'Desempenho comercial':'Resultado por gestão'}" required></label><label class="field">Fonte<select><option>${commercial?'Vendas realizadas':'Realizado financeiro'}</option><option>${commercial?'Vendas planejadas':'Budget oficial'}</option></select></label><label class="field">Eixo das linhas<select><option>${commercial?'Vendedor':'Conta contábil'}</option><option>${commercial?'Mês':'Gestão'}</option><option>${commercial?'Cultura':'Centro de custo'}</option></select></label><label class="field">Métrica<select><option>Faturamento</option><option>Margem</option>${commercial?'':'<option>Saldo da conta</option>'}</select></label><label class="field">Formato<select><option>R$ milhões</option><option>Moeda</option><option>Percentual</option></select></label><label class="field full">${commercial?'Elegibilidade (campanha)':'Fórmula da linha'}<input value="${commercial?'Vendedor · elegível · vigência ativa':'[Receita líquida] - [OPEX]'}"></label></div><div class="form-actions"><button type="submit" class="btn primary">Salvar relatório</button></div></form>`)}${panel('Pré-visualização','Exemplo ilustrativo da configuração',table(commercial?['Vendedor','Faturamento','Meta','Atingimento']:['Gestão','Realizado','Budget','Δ %'],commercial?[['Lucas Martins',money(4.2),money(4),badge('105,0%','good')],['Ana Ferreira',money(3.6),money(3.8),badge('94,7%','warn')]]:financialRows([['Industrial',4.8,5],['Comercial',2.4,2.5],['Administrativo',2.4,2.6]])))}</div>`;}
  function campaign(){return toolbar({noManagement:true})+kpis([['Faturamento elegível',money(7.8),'100,0%','da meta'],['Participantes','2','Elegíveis','no período',''],['Meta',money(7.8),'Campanha','2026',''],['Premiação provisionada','R$ 42 mil','Não pago','situação','warn']])+panel('Resultado por participante','Campanha demonstrativa · provisão de premiação',table(['Participante','Cargo','Elegibilidade','Meta','Realizado','Atingimento','Provisão'],[['Lucas Martins','Vendedor',badge('Elegível','good'),money(4),money(4.2),'105,0%','R$ 42.000'],['Ana Ferreira','Representante',badge('Elegível','good'),money(3.8),money(3.6),'94,7%','R$ 0']],{numeric:false}));}
  function users(){return panel('Usuários do workspace','Perfis e concessões adicionais',table(['Usuário','E-mail','Perfil','Gestão','Status',''],[['Rafael Guimarães','rafael.exemplo@empresa.test','Administrador','Marcher','Ativo'],['Marina Costa','marina.exemplo@empresa.test','Gestor','Industrial','Ativo'],['Lucas Martins','lucas.exemplo@empresa.test','Comercial','Comercial','Ativo'],['Ana Ferreira','ana.exemplo@empresa.test','Analista','Supply Chain','Ativo']].map((r,i)=>[...r.map((v,j)=>j===0?`<button class="table-link" data-action="user:${i}"><span class="avatar">${v.split(' ').map(x=>x[0]).join('')}</span>${v}</button>`:j===4?badge(v,'good'):esc(v)),button('Permissões',`user:${i}`,'shield','ghost')]),{numeric:false}),tableSearch());}
  function profiles(){return panel('Papéis de acesso','Catálogo visual · permissões reais continuam definidas no produto',table(['Perfil','Escopo principal','Concessões adicionais'],[['Super Admin','Administração total da organização','Todas'],['Administrador','Parâmetros, cargas, usuários e relatórios','Gestões, CCs, contas, relatórios e filiais'],['Gestor','Dashboard e relatórios por gestão','Gestões e CCs adicionais'],['Analista','Relatórios restritos por centro de custo','Contas, relatórios e filiais'],['Comercial','Painel, mapas e RPS Comercial','Relatórios comerciais'],['RPS Gestão','Indicadores e reunião semanal','Perfil adicional'],['Gestão Estratégica','A3, indicadores e planos de ação','Concessões de A3']],{numeric:false,hint:'Especificação visual, sem autenticação real'}));}
  function notices(admin=false){return admin?panel('Comunicados','Notificações ativas e agendadas',table(['Título','Público','Canal','Agendamento','Status',''],[['Carga de setembro disponível','Gestores','Sistema e e-mail','22/09/2026 · 16:42',badge('Ativo','good'),button('Editar','notificationEdit','edit','ghost')],['Atualização dos A3','Gestão Estratégica','Sistema','25/09/2026 · 09:00',badge('Agendado','blue'),button('Editar','notificationEdit','edit','ghost')]],{numeric:false})):panel('Recentes','Atualizações relevantes para você',`<div class="panel-body notice-list">${[['Carga de setembro disponível','A carga de realizado foi aplicada. Os relatórios estão atualizados.','Há 20 minutos','actualsLoad'],['Plano de ação · Industrial','A revisão do sequenciamento vence em 30 de setembro.','Há 1 hora','a3Actions'],['Mensagem de Marina Costa','Podemos revisar os indicadores antes da reunião?','Há 2 horas','messages']].map(([title,desc,time,id])=>`<div class="notice">${icon('bell')}<div class="spacer"><h3>${title}</h3><p class="muted">${desc}</p><span class="meta">${time}</span></div>${link('Abrir',id,'arrow','ghost')}</div>`).join('')}</div>`);}
  function messages(){return `<section class="panel messages"><aside class="contacts"><label class="field">Conversas<input type="search" data-contact-search placeholder="Buscar contato…"></label>${['Marina Costa','Lucas Martins','Ana Ferreira'].map((n,i)=>`<button class="contact ${state.conversation===n?'active':''}" data-contact="${n}"><span class="avatar">${n.split(' ').map(x=>x[0]).join('')}</span><span><strong>${n}</strong><small>${i?'Vamos alinhar a próxima semana.':'Revisão dos indicadores'}</small></span></button>`).join('')}</aside><div class="chat"><div class="row"><span class="avatar">${state.conversation.split(' ').map(x=>x[0]).join('')}</span><div><h3>${state.conversation}</h3><span class="meta">Conversa demonstrativa</span></div></div><div class="chat-body"><span class="meta" style="align-self:center">Hoje · 23 de setembro</span><div class="bubble">Podemos revisar os indicadores antes da reunião?<small>09:41</small></div><div class="bubble mine">Sim. Já deixei os relatórios e o plano de ação organizados.<small>09:42 · Lida</small></div>${state.messages.filter(m=>m.contact===state.conversation).map(m=>`<div class="bubble mine">${esc(m.text)}<small>Agora · Simulação local</small></div>`).join('')}</div><form data-chat-form><input aria-label="Mensagem" name="message" placeholder="Escreva uma mensagem…" required autocomplete="off"><button class="btn primary" aria-label="Enviar mensagem demonstrativa">${icon('arrow')}</button></form></div></section>`;}
  function profile(){return `<div class="grid2 equal">${panel('Informações pessoais','Seu perfil no workspace',`<form class="panel-body" data-local-form="profile"><div class="row" style="margin-bottom:24px"><span class="avatar" style="width:56px;height:56px;font-size:16px">RG</span><div><h3>Rafael Guimarães</h3><span class="meta">Administrador · Marcher Brasil</span></div></div><div class="form-grid"><label class="field full">Nome<input value="Rafael Guimarães" required></label><label class="field full">E-mail<input type="email" value="rafael.exemplo@empresa.test" required></label><label class="field">Departamento<input value="Controladoria"></label><label class="field">Telefone<input type="tel" placeholder="(00) 00000-0000"></label></div><div class="form-actions"><button class="btn primary">Salvar perfil</button></div></form>`)}${panel('Aparência','A mesma plataforma, no tema que funciona para você',`<div class="panel-body stack">${themeSwitch()}<p class="small muted">A preferência de tema é mantida neste navegador. Todas as telas usam a mesma seleção.</p><div class="panel" style="padding:20px"><span class="meta">Prévia de leitura</span><h2 style="margin-top:8px">R$ 42,0 mi</h2><span class="small positive">+4,3% vs Budget</span></div>${link('Gerenciar senha','resetPassword','lock')}${link('Visualizar tela de acesso','login','arrow','ghost')}</div>`)}</div>`;}
  function auth(s){const isLogin=s.id==='login',forgot=s.id==='forgotPassword';return `<div class="auth-layout"><section class="auth-story">${brand()}<div><span class="eyebrow">Gestão · planejamento · analytics</span><h1>Clareza para decidir.<br>Precisão para crescer.</h1><p>Resultados, pessoas e estratégia conectados em uma única visão de negócio.</p>${chart('line',[22,26,25,31,30,36,38,39,42])}<span class="meta">Visualização ilustrativa · Vecton Planning</span></div><span class="meta">Marcher Brasil · Workspace corporativo</span></section><section class="auth-form-region"><div class="auth-form">${brand()}<h1>${s.title}</h1><p class="muted">${s.description}</p><form data-auth-form><label class="field">E-mail corporativo<input type="email" name="email" autocomplete="username" placeholder="seu.email@empresa.com.br" required></label>${forgot?'':`<label class="field">${isLogin?'Senha':'Nova senha'}<input type="password" name="password" autocomplete="${isLogin?'current-password':'new-password'}" minlength="8" placeholder="Mínimo de 8 caracteres" required></label>`}${!forgot&&!isLogin?'<label class="field">Confirmar senha<input type="password" name="confirm" autocomplete="new-password" minlength="8" required></label>':''}${isLogin?`<div style="text-align:right">${link('Esqueci minha senha','forgotPassword','','ghost')}</div>`:''}<button class="btn primary" type="submit">${forgot?'Enviar instruções':isLogin?'Entrar no Vecton':'Salvar e continuar'}${icon('arrow')}</button></form><div class="auth-foot">${link(isLogin?'Explorar o mockup sem login':'Voltar ao acesso',isLogin?'dashboard':'login','','ghost')}</div>${themeSwitch()}<p class="meta" style="margin-top:24px;text-align:center">Protótipo visual · não utilize credenciais reais</p></div></section></div>`;}
  function designSystem(){const tokens=['background','background-secondary','surface','surface-elevated','border','border-subtle','text-primary','text-secondary','text-muted','accent','success','warning','danger','info'];return panel('Tokens semânticos',`Tema ${state.theme==='clear'?'Clear':'Dark'} · superfícies, texto e estados`,`<div class="panel-body swatches">${tokens.map(t=>`<div class="swatch"><i style="background:var(--${t})"></i>${t}</div>`).join('')}</div>`)+`<div class="grid2 equal" style="margin-top:24px">${panel('Tipografia e hierarquia','Inter / Segoe UI · números tabulares',`<div class="panel-body stack"><h1>Título da página · 28 / 600</h1><h2>Título de seção · 19 / 600</h2><h3>Título de agrupamento · 14 / 600</h3><p>Texto principal · 14 / 400</p><span class="meta">Metadados · 12 / 400</span><div class="kpi-value">R$ 42,0 mi</div></div>`)}${panel('Componentes e estados','Uma ação principal por contexto',`<div class="panel-body stack"><div class="row wrap">${button('Primário','sample','check','primary')}${button('Secundário','sample','plus')}${button('Ghost','sample','','ghost')}<button class="btn" disabled>Desabilitado</button></div><div class="row wrap">${badge('No prazo','good')}${badge('Em atenção','warn')}${badge('Erro','bad')}${badge('Selecionado','blue')}</div><label class="field">Campo com label<input placeholder="Conteúdo do campo"></label><span class="meta">Espaçamento: 4 / 8 / 12 / 16 / 20 / 24 / 32 / 40 / 48 / 64</span>${button('Inspecionar estados de tela','review','layers')}</div>`)}</div>`;}
  function index(){const groups=[...new Set(C.map(s=>s.group))];return `<div class="toolbar"><input type="search" placeholder="Buscar uma tela…" aria-label="Buscar telas" data-index-search style="width:320px"><span class="meta">${C.length} telas · Clear e Dark · desktop e mobile</span></div>${groups.map(g=>`<section class="catalog-section"><div class="section-title"><h2>${g}</h2><span class="meta">${C.filter(s=>s.group===g).length} telas</span></div><div class="screen-index">${C.filter(s=>s.group===g).map(s=>`<button data-go="${s.id}">${icon('reports')}<span>${esc(s.title)}<small>${esc(s.description)}</small><code>${s.id}</code></span></button>`).join('')}</div></section>`).join('')}`;}
  function body(s){switch(s.kind){
    case'dashboard':return executive();case'cockpit':return cockpit();case'catalog':return catalog();case'parameters':case'commercialParameters':return catalog(s.kind);case'sales':return sales();case'salesMatrix':return sales(true);case'map':return geographic();case'parts':return geographic(true);case'dre':case'opex':case'headcount':case'customReport':return financial(s);case'cashflow':return cashflow();case'fcDetail':return cashDetail();case'planning':return planning();case'fcScenarios':return cashScenarios();case'scenario':return scenario();case'compare':return scenario(true);case'registry':return registry(s);case'tree':return tree(s);case'import':return imports(s);case'importReview':return importReview();case'strategic':return strategic();case'a3Detail':return a3();case'a3Entry':return a3(true);case'actions':return actions();case'rps':return rps();case'presentation':return rps(true);case'rpsCommercial':return rpsCommercial();case'commercialPresentation':return rpsCommercial(true);case'history':return history();case'archived':return history(true);case'builder':return builder();case'commercialBuilder':return builder(true);case'campaign':return campaign();case'users':return users();case'accessProfiles':return profiles();case'notifications':return notices(true);case'inbox':return notices();case'messages':return messages();case'profile':return profile();case'designSystem':return designSystem();case'screenIndex':return index();default:return catalog();}}
  function pageActions(s){if(s.kind==='registry')return button('Novo registro','newRecord','plus','primary');if(s.kind==='tree')return button('Novo item','newTree','plus','primary');if(s.kind==='planning')return button('Novo cenário','newScenario','plus','primary');if(s.kind==='fcScenarios')return link('Nova simulação','fcDetail','plus','primary');if(s.kind==='catalog')return link('Criar relatório','reportBuilder','plus','primary');if(s.kind==='users')return button('Convidar usuário','inviteUser','users-plus','primary');if(s.kind==='notifications')return button('Nova notificação','notificationEdit','plus','primary');if(s.kind==='strategic')return button('Criar A3','newA3','plus','primary');if(s.kind==='actions')return button('Nova ação','editAction','plus','primary');if(s.kind==='rps')return link('Apresentar','rpsPresentation','reports','primary');if(s.kind==='rpsCommercial')return link('Apresentar','rpsCommercialPresentation','reports','primary');if(['presentation','commercialPresentation'].includes(s.kind))return link('Sair da apresentação',s.kind==='presentation'?'rps':'rpsComercial','back');if(s.kind==='builder')return link('Criador comercial','commercialBuilder','arrow');if(s.kind==='cashflow')return link('Cenários','fcScenarios','layers')+button('Exportar','export','download');if(['dashboard','cockpit','sales','salesMatrix','map','parts','dre','opex','headcount','customReport','campaign'].includes(s.kind))return button('Exportar','export','download');if(s.kind==='screenIndex')return button('Estados de tela','review','layers');return '';}
  function stateView(){const text={empty:['Nenhum dado neste período','Escolha outra competência ou faça uma nova carga de dados.','reports'],error:['Não foi possível carregar os dados','O conteúdo já carregado foi preservado. Tente novamente.','activity'],noResults:['Nenhum resultado encontrado','Ajuste a busca ou remova os filtros ativos.','search'],loading:['Carregando dados','Estamos preparando esta visão.','refresh']};const [title,desc,ico]=text[state.ui]||text.empty;return `<section class="panel state-panel" aria-live="polite">${state.ui==='loading'?'<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>':icon(ico)}<h2>${title}</h2><p class="muted small">${desc}</p>${button(state.ui==='error'?'Tentar novamente':'Voltar à visualização','retry',state.ui==='error'?'refresh':'back')}</section>`;}
  function render(){const s=screen();document.documentElement.dataset.theme=state.theme;document.title=`${s.title} · Vecton Mockup`;document.body.classList.remove('menu-open');$('#app').innerHTML=s.kind==='auth'?auth(s):`${sidebar()}<div class="shell">${topbar()}<main id="main" tabindex="-1"><div class="page-heading"><div><div class="eyebrow">${esc(s.group)}</div><h1>${esc(s.title)}</h1><p>${esc(s.description)}</p></div><div class="row gap8 wrap">${pageActions(s)}</div></div>${state.review?`<div class="review-bar"><span>Avaliação visual · estados compartilhados</span><label>Estado <select data-ui-state>${[['success','Sucesso'],['loading','Carregando'],['empty','Vazio'],['noResults','Sem resultados'],['error','Erro']].map(([v,t])=>`<option value="${v}" ${state.ui===v?'selected':''}>${t}</option>`).join('')}</select></label>${button('Fechar','review','close','ghost')}</div>`:''}<div id="screen-content">${state.ui==='success'?body(s):stateView()}</div><footer class="footer"><span>Vecton Planning · Protótipo para avaliação · Dados demonstrativos</span><div class="row">${button('Estados de tela','review','','ghost')}${link(`${C.length} telas disponíveis`,'screenIndex','','ghost')}</div></footer></main></div>`;}
  function go(id){if(!C.some(s=>s.id===id))return;if(dialog.open)dialog.close();state.id=id;state.ui='success';state.tab='Todos';state.treeName='';state.scope='Todos';location.hash=id;render();window.scrollTo(0,0);$('#main')?.focus({preventScroll:true});}
  let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4000);}
  const dialog=$('#dialog');let returnFocus;
  function modal(title,html,drawer=false){returnFocus=document.activeElement;dialog.className=drawer?'drawer':'';dialog.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${esc(title)}</h2><button class="btn ghost icon-btn" data-action="close" aria-label="Fechar janela">${icon('close')}</button></div><div class="dialog-body">${html}</div>`;if(!dialog.open)dialog.showModal();}
  dialog.addEventListener('close',()=>returnFocus?.isConnected&&returnFocus.focus());
  function formModal(title,fields,type='generic'){modal(title,`<p>Prévia de edição · os dados ficam apenas nesta sessão demonstrativa.</p><form data-modal-form="${type}" class="form-grid">${fields.map(([label,value='',kind='text'],i)=>`<label class="field ${i===0?'full':''}">${esc(label)}${kind==='textarea'?`<textarea name="f${i}" required>${esc(value)}</textarea>`:`<input name="f${i}" type="${kind}" value="${esc(value)}" required>`}</label>`).join('')}<div class="form-actions field full"><button class="btn primary" type="submit">${type==='invite'?'Simular convite':'Salvar no mockup'}</button></div></form>`);}
  function showDrill(name,type){let headers,rows;if(type==='people'){headers=['Matrícula','Colaborador','Cargo','Centro de custo'];rows=[['001','Marina Costa','Analista','Industrial'],['002','Lucas Martins','Coordenador','Comercial'],['003','Ana Ferreira','Analista','Supply Chain']];}else if(type==='sales'){headers=['Cliente','SKU','Volume','Faturamento'];rows=[['Agro Horizonte','MAQ-001','3','R$ 900.000'],['Fazenda Primavera','MAQ-002','2','R$ 600.000']];}else if(type==='kpi'){headers=['Período','Meta','Realizado','Situação'];rows=[['Jul/2026','85,0%','86,0%',badge('Na meta','good')],['Ago/2026','85,0%','87,0%',badge('Na meta','good')],['Set/2026','85,0%','88,2%',badge('Na meta','good')]];}else{headers=['Data','Conta / histórico','Centro de custo','Valor'];rows=[['05/09/2026','31101001 · Lançamento demonstrativo','Industrial','R$ 120.000'],['12/09/2026','31101002 · Lançamento demonstrativo','Comercial','R$ 85.000'],['18/09/2026','31101003 · Lançamento demonstrativo','Supply Chain','R$ 64.000']];}modal(name,`<p>${esc(state.month)}/2026 · ${esc(state.period)} · ${esc(state.management)}<br>Detalhamento ilustrativo do fluxo de navegação.</p>${table(headers,rows,{numeric:false,hint:'Amostra demonstrativa, sem conciliação contábil'})}<div class="form-actions">${button('Exportar detalhe','export','download')}</div>`,true);}
  function search(){modal('Buscar no Vecton',`<label class="field">Telas e funcionalidades<input type="search" data-global-search placeholder="Busque por DRE, pessoas, A3, cargas…" autofocus></label><div class="search-results">${searchItems('')}</div>`);}
  function searchItems(q){return C.filter(s=>(s.title+' '+s.description).toLocaleLowerCase('pt-BR').includes(q.toLocaleLowerCase('pt-BR'))).map(s=>`<button data-go="${s.id}"><span>${esc(s.title)}</span><small class="meta">${s.group}</small></button>`).join('')||'<p>Nenhuma tela encontrada.</p>';}
  const actionsMap={
    close:()=>dialog.close(),menu:()=>document.body.classList.toggle('menu-open'),collapse:()=>document.body.classList.toggle('compact'),search,
    notifications:()=>modal('Notificações',notices()+`<div class="form-actions">${link('Ver todas','inbox','arrow')}</div>`,true),
    review:()=>{state.review=!state.review;state.ui='success';render();},retry:()=>{state.ui='success';render();},
    newRecord:()=>{state.editRow=null;formModal(`Novo registro · ${screen().title}`,screen().columns.map(n=>[n]),'record');},
    newTree:()=>formModal('Novo item da estrutura',[['Descrição'],['Código'],['Classe','Analítica'],['Grupo superior','1']],'tree'),
    newScenario:()=>formModal('Novo cenário de forecast',[['Nome','Forecast 8+4'],['Fonte','Budget oficial'],['Meses realizados','8'],['Ano','2026']],'scenario'),
    newA3:()=>formModal('Criar A3',[['Nome da área'],['Objetivo estratégico','','textarea'],['Responsável'],['Ciclo','2026']],'a3'),
    editAction:()=>formModal('Plano de ação',[['Ação','Revisar sequência de produção'],['Responsável','Marina Costa'],['Prazo','2026-09-30','date'],['Análise e contramedida','Revisar o sequenciamento para reduzir restrições de entrega.','textarea']]),
    northGoals:()=>formModal('Norte Verdadeiro · metas anuais',[['Receita líquida','R$ 504 mi'],['Margem EBITDA','20,0%'],['Entregas no prazo','95,0%'],['NPS','85 pontos']]),
    inviteUser:()=>formModal('Convidar usuário',[['Nome'],['E-mail','','email'],['Perfil','Analista'],['Gestão','Industrial']],'invite'),
    notificationEdit:()=>formModal('Notificação',[['Título','Atualização dos indicadores'],['Mensagem','','textarea'],['Público','Gestores'],['Agendamento','2026-09-25T09:00','datetime-local']]),
    saveScenario:()=>toast('Alterações do cenário simuladas nesta sessão.'),saveEntries:()=>toast('Lançamentos salvos no mockup. Nenhum dado foi enviado.'),saveRps:()=>toast('Semana salva na simulação.'),saveComment:()=>toast('Comentário salvo na simulação.'),sample:()=>toast('Estado de sucesso do componente.'),
    saveFc:()=>formModal('Salvar novo cenário de caixa',[['Nome','Caixa · simulação Setembro'],['Visibilidade','Compartilhado (Administrador)']],'fc'),
    fcUndo:()=>{window.MOCKUP_CASH.reset();render();toast('Simulação de caixa restaurada.');},openFc:()=>go('fcDetail'),
    validate:()=>{state.importStep=2;$('#screen-content').innerHTML=insight('Lote demonstrativo validado.', '1.248 linhas válidas e nenhuma inconsistência. A aplicação abaixo é simulada.')+panel('Prévia da carga','Registros do exemplo',table(['Linha','Conta','Centro de custo','Valor'],[['1','31101001','Industrial','R$ 120.000'],['2','31101002','Comercial','R$ 85.000']],{numeric:false}))+`<div class="form-actions">${button('Aplicar lote demonstrativo','applyImport','check','primary')}</div>`;},
    applyImport:()=>{modal('Aplicação concluída',`<p>Lote demonstrativo aplicado com sucesso. Nenhum dado foi enviado ao servidor.</p>${badge('1.248 linhas · Aplicado','good')}<div class="form-actions">${link('Voltar às cargas','actualsLoad','arrow','primary')}</div>`);},
    restore:()=>modal('Restaurar item arquivado',`<p>O item voltará à lista de áreas nesta simulação.</p>${button('Restaurar no mockup','confirmRestore','refresh','primary')}`),
    confirmRestore:()=>{dialog.close();go('strategic');toast('Restauração simulada.');},
    closePeriod:()=>modal('Fechar competência do A3',`<p>O fechamento preserva o retrato dos indicadores e bloqueia edições da competência. Esta ação é demonstrativa e específica do A3.</p>${button('Simular fechamento','confirmClose','lock','primary')}`),
    confirmClose:()=>{dialog.close();toast('Fechamento simulado para o A3 Industrial.');},
    snapshot:()=>modal('RPS · versão de 22/09/2026',`<p>Snapshot demonstrativo de Setembro/2026. Integridade verificada.</p>${table(['Indicador','Realizado','Meta'],[['Eficiência operacional','88,2%','85,0%'],['Entregas no prazo','92,4%','95,0%']])}<div class="form-actions">${button('Simular restauração','confirmRestore','refresh')}</div>`,true),
    attachment:()=>modal('Evidências e anexos',`<p>Revise o arquivo e mantenha o contexto da análise. Uploads ficam apenas na prévia local.</p><label class="field">Arquivo de evidência<input type="file" data-attachment-file></label><div id="attachment-preview" class="stack" style="margin:20px 0"></div><label class="field">Comentário<textarea placeholder="Adicione contexto para a equipe…"></textarea></label><div class="form-actions">${button('Salvar comentário','attachmentSave','check','primary')}</div>`),
    attachmentSave:()=>{dialog.close();toast('Comentário de evidência registrado na simulação.');},
    export:()=>modal('Exportar visualização',`<p>${esc(screen().title)} · ${esc(state.month)}/2026 · ${esc(state.period)}<br>Exporte os valores demonstrativos exibidos.</p><div class="stack">${button('Baixar tabela CSV','downloadCsv','download')}${button('Imprimir / salvar PDF','print','reports')}${button('Prévia de envio por e-mail','emailPreview','mail')}</div>`),
    downloadCsv:()=>{const t=$('#main table')||dialog.querySelector('table');if(!t){toast('Esta tela não possui uma tabela. Use Imprimir / salvar PDF.');return;}const rows=[...t.rows].map(r=>[...r.cells].map(c=>'"'+c.innerText.replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+rows],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`vecton-mockup-${state.id}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);dialog.close();toast('Tabela demonstrativa exportada.');},
    print:()=>{dialog.close();window.print();},emailPreview:()=>formModal('Prévia de envio por e-mail',[['Para','','email'],['Assunto',screen().title],['Mensagem','Segue a visão do período selecionado.','textarea']],'email')
  };
  document.addEventListener('click',e=>{
    const target=e.target.closest('button,[data-drill],[data-tree]');if(!target)return;
    if(target.dataset.go){if(dialog.open)dialog.close();go(target.dataset.go);return;}
    if(target.dataset.themeChoice){state.theme=target.dataset.themeChoice;try{localStorage.setItem('vecton-mockup-theme',state.theme);}catch{}render();return;}
    if(target.dataset.period){state.period=target.dataset.period;render();return;}
    if(target.dataset.region){state.region=target.dataset.region;render();return;}
    if(target.dataset.tab){state.tab=target.dataset.tab;render();return;}
    if(target.dataset.reportTab){const t=target.dataset.reportTab;if(screen().kind==='dre'){go(`dre${{'Societário':'Soc','Gerencial':'Ger','DFs':'Dfs'}[t]}${state.id.includes('Budget')?'Budget':'Real'}`);}else{state.tab=t;render();}return;}
    if(target.dataset.drill){showDrill(target.dataset.drill,target.dataset.drillType);return;}
    if(target.dataset.tree){state.treeName=target.dataset.tree;render();return;}
    if(target.dataset.favorite){state.favorite=target.dataset.favorite;render();toast(`${state.favorite} definido como favorito no mockup.`);return;}
    if(target.dataset.contact){state.conversation=target.dataset.contact;render();return;}
    if(target.dataset.editRow!==undefined){state.editRow=Number(target.dataset.editRow);const s=screen(),r=(state.localRows[s.id]||D.registries[s.id])[state.editRow];formModal(`Editar · ${s.title}`,s.columns.map((n,i)=>[n,r[i]]),'record');return;}
    if(target.dataset.sort!==undefined){const t=target.closest('table'),idx=Number(target.dataset.sort),dir=target.dataset.direction==='asc'?-1:1;target.dataset.direction=dir===1?'asc':'desc';target.closest('th').setAttribute('aria-sort',dir===1?'ascending':'descending');const rows=[...t.tBodies[0].rows];rows.sort((a,b)=>a.cells[idx].textContent.localeCompare(b.cells[idx].textContent,'pt-BR',{numeric:true})*dir).forEach(r=>t.tBodies[0].append(r));return;}
    const action=target.dataset.action;if(!action)return;
    if(action.startsWith('cashOpen:')){window.MOCKUP_CASH.open(Number(action.split(':')[1]));go('fcDetail');return;}
    if(action.startsWith('saveRpsBlock:')){const i=action.split(':')[1];state.formDraft[`rps${state.region}${i}`]=$(`#rps-text-${i}`).value;toast('Bloco salvo no mockup.');return;}
    if(action.startsWith('user:')){modal('Perfil e concessões',`<p>Permissões adicionais do usuário. Prévia visual da administração.</p><form data-modal-form="generic" class="form-grid"><label class="field full">Perfil<select><option>Gestor</option><option>Analista</option><option>Comercial</option><option>Administrador</option></select></label>${['Gestão principal','Gestões adicionais','Centros de custo','Contas contábeis','Relatórios adicionais','Filiais','A3 permitidos'].map(n=>`<label class="field">${n}<input placeholder="Selecionar…"></label>`).join('')}<div class="form-actions field full"><button class="btn primary">Salvar permissões no mockup</button></div></form>`,true);return;}
    if(action.startsWith('template:')){formModal('Configurar relatório comercial',[['Nome',['Desempenho de um vendedor','Comparativo do time','Performance por vendedor e cultura','Campanha comercial'][Number(action.split(':')[1])]],['Vigência','2026'],['Métrica','Faturamento'],['Público','Time comercial']],'commercialReport');return;}
    actionsMap[action]?.();
  });
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search();}if(e.key==='Escape'){document.body.classList.remove('menu-open');if(dialog.open){e.preventDefault();dialog.close();}}if((e.key==='Enter'||e.key===' ')&&e.target.matches('path[data-drill]')){e.preventDefault();showDrill(e.target.dataset.drill,'sales');}});
  document.addEventListener('input',e=>{const t=e.target;
    if(t.matches('[data-global-search]'))dialog.querySelector('.search-results').innerHTML=searchItems(t.value);
    if(t.matches('[data-table-search]')){const rows=[...document.querySelectorAll('#main tbody tr')];let count=0;rows.forEach(r=>{r.hidden=!r.textContent.toLowerCase().includes(t.value.toLowerCase());if(!r.hidden)count++;});let msg=$('#no-search-results');if(!msg){msg=document.createElement('p');msg.id='no-search-results';msg.className='insight';$('#screen-content').append(msg);}msg.textContent='Nenhum resultado para esta busca.';msg.hidden=count>0;}
    if(t.matches('[data-catalog-search],[data-index-search]')){const selector=t.matches('[data-index-search]')?'.screen-index button':'.catalog-card';document.querySelectorAll(selector).forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(t.value.toLowerCase()));document.querySelectorAll('.catalog-section').forEach(s=>s.hidden=![...s.querySelectorAll(selector)].some(b=>!b.hidden));}
    if(t.matches('[data-tree-search]'))document.querySelectorAll('.tree-row').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(t.value.toLowerCase()));
    if(t.matches('[data-contact-search]'))document.querySelectorAll('.contact').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(t.value.toLowerCase()));
  });
  document.addEventListener('change',e=>{const t=e.target;
    if(t.dataset.filter){state[t.dataset.filter]=t.value;render();}
    if(t.matches('[data-ui-state]')){state.ui=t.value;render();}
    if(t.matches('[data-upload]')&&t.files.length){state.importStep=1;go('importReview');toast(`Arquivo ${t.files[0].name} selecionado. Validação exibida é um exemplo visual.`);}
    if(t.matches('[data-fc-input]')){const val=Number(t.value.replaceAll('.','').replace(',','.'));if(!t.value.trim()||!window.MOCKUP_CASH.update(Number(t.dataset.fcMonth),t.dataset.fcInput,val)){t.setCustomValidity('Informe um número válido. Quantidades devem ser inteiras e não negativas.');t.reportValidity();return;}t.setCustomValidity('');render();toast('Simulação recalculada. Meses realizados preservados.');}
    if(t.matches('[data-attachment-file]')&&t.files.length){const f=t.files[0];$('#attachment-preview').innerHTML=`<div class="attachment">${icon('reports')}${esc(f.name)} · ${br(f.size/1024,0)} KB</div><span class="meta">Arquivo selecionado localmente. Nenhum upload realizado.</span>`;}
  });
  document.addEventListener('submit',e=>{e.preventDefault();const f=e.target;
    if(f.matches('[data-chat-form]')){const text=new FormData(f).get('message').trim();if(text){state.messages.push({contact:state.conversation,text});render();}return;}
    if(f.matches('[data-auth-form]')){const fd=new FormData(f);if(fd.get('confirm')!==null&&fd.get('password')!==fd.get('confirm')){f.elements.confirm.setCustomValidity('As senhas devem ser iguais.');f.elements.confirm.reportValidity();f.elements.confirm.oninput=()=>f.elements.confirm.setCustomValidity('');return;}if(state.id==='forgotPassword'){modal('Instruções de recuperação',`<p>Prévia de sucesso: as instruções seriam enviadas ao e-mail informado. Este protótipo não envia e-mails.</p>${link('Voltar ao acesso','login','back')}`);}else go('dashboard');return;}
    if(f.matches('[data-local-form]')){toast('Alterações salvas na simulação visual.');return;}
    if(f.matches('[data-modal-form]')){const type=f.dataset.modalForm,values=[...new FormData(f).values()];if(type==='record'){const s=screen();state.localRows[s.id]=[...(state.localRows[s.id]||D.registries[s.id]||[])];if(state.editRow===null)state.localRows[s.id].push(values);else state.localRows[s.id][state.editRow]=values;}if(type==='fc')window.MOCKUP_CASH.save(values[0]);dialog.close();if(type==='scenario')go('scenarioEdit');else if(type==='fc')go('fcScenarios');else if(type==='a3')go('a3Detail');else if(type==='commercialReport')go('campaign');else render();toast(type==='email'?'Prévia preparada. Nenhum e-mail foi enviado.':type==='invite'?'Convite simulado. Nenhum e-mail foi enviado.':'Salvo no mockup para avaliação visual.');}
  });
  window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(id!==state.id){state.id=id;state.ui='success';state.tab='Todos';render();}});
  render();
  // Interface de inspeção apenas do protótipo: catálogo e estado, sem serviços.
  window.VECTON_MOCKUP = {screens:C,getState:()=>({...state}),navigate:go};
})();
